version: '3.8'

services:
  server:
    build:
      context: ../..
      dockerfile: src/server/Dockerfile
    image: thaily/lvtn-server:latest
    container_name: graphql_gateway
    env_file:
      - .server.env
    ports:
      - "8080:8080"
    volumes:
      - ./certs:/app/certs:ro
      - ../../logs:/app/logs
    networks:
      - lvtn_network
    restart: unless-stopped

networks:
  lvtn_network:
    driver: bridge
