type Faculty {
    id: ID!
    title: String!
    ms: String!
    createdAt: Time
    updatedAt: Time
    createdBy: String
    updatedBy: String

    majors: [Major!]!
}


type Major {
    id: ID!
    title: String!
    facultyCode: String!  # Chỉ có code, KHÔNG có faculty relationship (tránh circular)
    ms: String!
    createdAt: Time
    updatedAt: Time
    createdBy: String
    updatedBy: String
}


type Semester {
    id: ID!
    title: String!
    createdAt: Time
    updatedAt: Time
    createdBy: String
    updatedBy: String
}
