
type Student {
    id: ID!
    email: String!
    phone: String!
    username: String!
    gender: Gender
    majorCode: String!  # Chỉ có code, KHÔNG có major relationship (tránh circular)
    classCode: String
    semesterCode: String!  # Chỉ có code, KHÔNG có semester relationship (tránh circular)
    mssv: String!
    createdAt: Time
    updatedAt: Time
    createdBy: String
    updatedBy: String
}


type Teacher {
    id: ID!
    email: String!
    username: String!
    gender: Gender
    majorCode: String!  # Chỉ có code, KHÔNG có major relationship (tránh circular)
    semesterCode: String!  # Chỉ có code, KHÔNG có semester relationship (tránh circular)
    msgv: String!
    createdAt: Time
    updatedAt: Time
    createdBy: String
    updatedBy: String
    roles: [RoleSystem!]
}

