root = "."
testdata_dir = "testdata"
tmp_dir = "tmp-server"

[build]
  args_bin = []
  bin = "./tmp-server/server"
  cmd = "go build -o ./tmp-server/server ./src/server"
  delay = 1000
  exclude_dir = ["tmp-server", "vendor", "testdata", "proto", "src/service"]
  exclude_file = []
  exclude_regex = ["_test.go", ".pb.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["src/server", "src/config", "src/pkg", "src/router", "src/graph"]
  include_ext = ["go", "graphql", "gql"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors-server.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
