package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"thaily/src/graph/generated"
	"thaily/src/graph/model"
)

// Majors is the resolver for the majors field.
func (r *facultyResolver) Majors(ctx context.Context, obj *model.Faculty) ([]*model.Major, error) {
	panic(fmt.Errorf("not implemented: Majors - majors"))
}

// Topics is the resolver for the topics field.
func (r *majorResolver) Topics(ctx context.Context, obj *model.Major) ([]*model.Topic, error) {
	panic(fmt.Errorf("not implemented: Topics - topics"))
}

// Students is the resolver for the students field.
func (r *semesterResolver) Students(ctx context.Context, obj *model.Semester) ([]*model.Student, error) {
	panic(fmt.Errorf("not implemented: Students - students"))
}

// Teachers is the resolver for the teachers field.
func (r *semesterResolver) Teachers(ctx context.Context, obj *model.Semester) ([]*model.Teacher, error) {
	panic(fmt.Errorf("not implemented: Teachers - teachers"))
}

// Topics is the resolver for the topics field.
func (r *semesterResolver) Topics(ctx context.Context, obj *model.Semester) ([]*model.Topic, error) {
	panic(fmt.Errorf("not implemented: Topics - topics"))
}

// Faculty returns generated.FacultyResolver implementation.
func (r *Resolver) Faculty() generated.FacultyResolver { return &facultyResolver{r} }

// Major returns generated.MajorResolver implementation.
func (r *Resolver) Major() generated.MajorResolver { return &majorResolver{r} }

// Semester returns generated.SemesterResolver implementation.
func (r *Resolver) Semester() generated.SemesterResolver { return &semesterResolver{r} }

type facultyResolver struct{ *Resolver }
type majorResolver struct{ *Resolver }
type semesterResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *majorResolver) Faculty(ctx context.Context, obj *model.Major) (*model.Faculty, error) {
	panic(fmt.Errorf("not implemented: Faculty - faculty"))
}
*/
