package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"thaily/src/graph/generated"
	"thaily/src/graph/model"
)

// GetInfoStudent is the resolver for the getInfoStudent field.
func (r *queryResolver) GetInfoStudent(ctx context.Context) (*model.Student, error) {
	return r.Ctrl.GetInfoStudent(ctx)
}

// GetInfoTeacher is the resolver for the getInfoTeacher field.
func (r *queryResolver) GetInfoTeacher(ctx context.Context) (*model.Teacher, error) {
	return r.Ctrl.GetInfoTeacher(ctx)
}

// GetListTopic is the resolver for the getListTopic field.
func (r *queryResolver) GetListTopic(ctx context.Context, search model.SearchRequestInput) ([]*model.Topic, error) {
	return r.Ctrl.GetTopics(ctx, search)
}

// GetListEnrollment is the resolver for the getListEnrollment field.
func (r *queryResolver) GetListEnrollment(ctx context.Context, search model.SearchRequestInput) ([]*model.Enrollment, error) {
	return r.Ctrl.GetEnrollments(ctx, search)
}

// GetListSemester is the resolver for the getListSemester field.
func (r *queryResolver) GetListSemester(ctx context.Context, search model.SearchRequestInput) ([]*model.Semester, error) {
	return r.Ctrl.GetSemesters(ctx, search)
}

// GetListCouncil is the resolver for the getListCouncil field.
func (r *queryResolver) GetListCouncil(ctx context.Context, search model.SearchRequestInput) ([]*model.Council, error) {
	panic(fmt.Errorf("not implemented: GetListCouncil - getListCouncil"))
}

// GetListDefence is the resolver for the getListDefence field.
func (r *queryResolver) GetListDefence(ctx context.Context, search model.SearchRequestInput) ([]*model.Defence, error) {
	panic(fmt.Errorf("not implemented: GetListDefence - getListDefence"))
}

// GetListSchedule is the resolver for the getListSchedule field.
func (r *queryResolver) GetListSchedule(ctx context.Context, search model.SearchRequestInput) ([]*model.CouncilSchedule, error) {
	panic(fmt.Errorf("not implemented: GetListSchedule - getListSchedule"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
