package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"thaily/src/graph/generated"
	"thaily/src/graph/model"
)

// GetInfoStudent is the resolver for the getInfoStudent field.
func (r *queryResolver) GetInfoStudent(ctx context.Context) (*model.Student, error) {
	return r.Ctrl.GetInfoStudent(ctx)
}

// GetInfoTeacher is the resolver for the getInfoTeacher field.
func (r *queryResolver) GetInfoTeacher(ctx context.Context) (*model.Teacher, error) {
	return r.Ctrl.GetInfoTeacher(ctx)
}

// GetListTopic is the resolver for the getListTopic field.
func (r *queryResolver) GetListTopic(ctx context.Context) (*model.Topic, error) {
	panic(fmt.Errorf("not implemented: GetListTopic - getListTopic"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
