package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"thaily/src/graph/generated"
	"thaily/src/graph/model"
)

// CreateMessage is the resolver for the createMessage field.
func (r *mutationResolver) CreateMessage(ctx context.Context, input string) (string, error) {
	panic(fmt.Errorf("not implemented: CreateMessage - createMessage"))
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, input model.Login) (*model.CommonResponse, error) {
	return r.Ctrl.Login(ctx, input)
}

// GetTopic is the resolver for the getTopic field.
func (r *queryResolver) GetTopic(ctx context.Context, input model.GetTopicInput) (*model.CommonResponse, error) {
	return r.Ctrl.GetTopic(ctx, input)
}

// Info is the resolver for the info field.
func (r *queryResolver) Info(ctx context.Context, input model.Info) (*model.CommonResponse, error) {
	return r.Ctrl.Info(ctx, input)
}

// Semesters is the resolver for the semesters field.
func (r *queryResolver) Semesters(ctx context.Context) (*model.CommonResponse, error) {
	return r.Ctrl.Semester(ctx)
}

// GetCouncil is the resolver for the getCouncil field.
func (r *queryResolver) GetCouncil(ctx context.Context, input model.GetCouncilInput) (*model.CommonResponse, error) {
	return r.Ctrl.GetCouncil(ctx, input)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
