package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"thaily/src/server/graph/dataloader"
	"thaily/src/server/graph/generated"
	"thaily/src/server/graph/model"
)

// Majors is the resolver for the majors field.
func (r *facultyResolver) Majors(ctx context.Context, obj *model.Faculty) ([]*model.Major, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.MajorByFacultyId != nil {
		return loaders.MajorByFacultyId.Load(ctx, obj.ID)
	}
	return r.Ctrl.GetMajorsByFacultyId(ctx, obj.ID)
}

// Faculty returns generated.FacultyResolver implementation.
func (r *Resolver) Faculty() generated.FacultyResolver { return &facultyResolver{r} }

type facultyResolver struct{ *Resolver }
