package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"thaily/src/server/graph/dataloader"
	"thaily/src/server/graph/generated"
	"thaily/src/server/graph/model"
)

// Defences is the resolver for the defences field.
// affair, department, council
func (r *councilResolver) Defences(ctx context.Context, obj *model.Council) ([]*model.Defence, error) {
	access, err := r.Resolver.RbacAccess(ctx, []string{"affair", "department", "council"})
	if err != nil {
		return nil, err
	}
	if !access {
		return nil, nil
	}
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.DefenceByCouncilId != nil {
		return loaders.DefenceByCouncilId.Load(ctx, obj.ID)
	}
	return r.Ctrl.GetDefencesByCouncilId(ctx, obj.ID)
}

// TopicCouncils is the resolver for the topicCouncils field.
func (r *councilResolver) TopicCouncils(ctx context.Context, obj *model.Council) ([]*model.TopicCouncil, error) {
	access, err := r.Resolver.RbacAccess(ctx, []string{"council", "affair", "department"})
	if err != nil {
		return nil, err
	}
	if !access {
		return nil, nil
	}
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.TopicCouncilByCouncilId != nil {
		return loaders.TopicCouncilByCouncilId.Load(ctx, obj.ID)
	}
	return r.Ctrl.GetTopicCouncilsByCouncilId(ctx, obj.ID)
}

// Council is the resolver for the council field.
func (r *defenceResolver) Council(ctx context.Context, obj *model.Defence) (*model.Council, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.CouncilByID != nil {
		council, err := loaders.CouncilByID.Load(ctx, obj.CouncilCode)
		if err != nil {
			return nil, err
		}
		return council, nil
	}

	return r.Ctrl.GetCouncilById(ctx, obj.CouncilCode)
}

// Teacher is the resolver for the teacher field.
func (r *defenceResolver) Teacher(ctx context.Context, obj *model.Defence) (*model.Teacher, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.TeacherById != nil {
		teacher, err := loaders.TeacherById.Load(ctx, obj.TeacherCode)
		if err != nil {
			return nil, err
		}
		return teacher, nil
	}

	return r.Ctrl.GetTeacherById(ctx, obj.TeacherCode)
}

// GradeDefences is the resolver for the gradeDefences field.
func (r *defenceResolver) GradeDefences(ctx context.Context, obj *model.Defence) ([]*model.GradeDefence, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.GradeDefenceByDefenceId != nil {
		gradeDefences, err := loaders.GradeDefenceByDefenceId.Load(ctx, obj.ID)
		if err != nil {
			return nil, err
		}
		return gradeDefences, nil
	}

	return r.Ctrl.GetGradeDefencesByDefenceId(ctx, obj.ID)
}

// Defence is the resolver for the defence field.
func (r *gradeDefenceResolver) Defence(ctx context.Context, obj *model.GradeDefence) (*model.Defence, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.DefenceById != nil {
		return loaders.DefenceById.Load(ctx, obj.DefenceCode)
	}
	return r.Ctrl.GetDefenceById(ctx, obj.DefenceCode)
}

// Enrollment is the resolver for the enrollment field.
func (r *gradeDefenceResolver) Enrollment(ctx context.Context, obj *model.GradeDefence) (*model.Enrollment, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.EnrollmentById != nil {
		return loaders.EnrollmentById.Load(ctx, obj.EnrollmentCode)
	}
	return r.Ctrl.GetEnrollmentById(ctx, obj.EnrollmentCode)
}

// Criteria is the resolver for the criteria field.
func (r *gradeDefenceResolver) Criteria(ctx context.Context, obj *model.GradeDefence) ([]*model.GradeDefenceCriterion, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.GradeDefenceCriteriaByDefenceId != nil {
		criteria, err := loaders.GradeDefenceCriteriaByDefenceId.Load(ctx, obj.ID)
		if err != nil {
			return nil, err
		}
		return criteria, nil
	}

	return r.Ctrl.GetGradeDefenceCriteriaByGradeDefenceId(ctx, obj.ID)
}

// Council returns generated.CouncilResolver implementation.
func (r *Resolver) Council() generated.CouncilResolver { return &councilResolver{r} }

// Defence returns generated.DefenceResolver implementation.
func (r *Resolver) Defence() generated.DefenceResolver { return &defenceResolver{r} }

// GradeDefence returns generated.GradeDefenceResolver implementation.
func (r *Resolver) GradeDefence() generated.GradeDefenceResolver { return &gradeDefenceResolver{r} }

type councilResolver struct{ *Resolver }
type defenceResolver struct{ *Resolver }
type gradeDefenceResolver struct{ *Resolver }
