package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code
// will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"thaily/src/server/graph/generated"
	"thaily/src/server/graph/model"
	"time"
)

// ============================================
// ROOT MUTATION ENTRY POINTS - Set role vào context
// ============================================

// Student is the resolver for the student field.
func (r *mutationResolver) Student(ctx context.Context) (*model.StudentMutation, error) {
	r.Resolver.RbacRoleDynamic(ctx, "student")
	return &model.StudentMutation{}, nil
}

// Teacher is the resolver for the teacher field.
func (r *mutationResolver) Teacher(ctx context.Context) (*model.TeacherMutation, error) {
	r.Resolver.RbacRoleDynamic(ctx, "teacher")
	return &model.TeacherMutation{}, nil
}

// Affair is the resolver for the affair field.
func (r *mutationResolver) Affair(ctx context.Context) (*model.AffairMutation, error) {
	r.Resolver.RbacRoleDynamic(ctx, "affair")
	return &model.AffairMutation{}, nil
}

// Department is the resolver for the department field.
func (r *mutationResolver) Department(ctx context.Context) (*model.DepartmentMutation, error) {
	r.Resolver.RbacRoleDynamic(ctx, "department")
	return &model.DepartmentMutation{}, nil
}

// ============================================
// STUDENT MUTATION NAMESPACE
// ============================================

// UploadMidtermFile is the resolver for the uploadMidtermFile field.
func (r *studentMutationResolver) UploadMidtermFile(ctx context.Context, obj *model.StudentMutation, input model.UploadFileInput) (*model.File, error) {
	return r.Ctrl.UploadMidtermFile(ctx, input)
}

// UploadFinalFile is the resolver for the uploadFinalFile field.
func (r *studentMutationResolver) UploadFinalFile(ctx context.Context, obj *model.StudentMutation, input model.UploadFileInput) (*model.File, error) {
	return r.Ctrl.UploadFinalFile(ctx, input)
}

// ============================================
// TEACHER MUTATION NAMESPACE
// ============================================

// UpdateProfile is the resolver for the updateProfile field.
func (r *teacherMutationResolver) UpdateProfile(ctx context.Context, obj *model.TeacherMutation, input model.UpdateTeacherProfileInput) (*model.Teacher, error) {
	return r.Ctrl.UpdateMyTeacherProfile(ctx, input)
}

// Supervisor is the resolver for the supervisor field.
func (r *teacherMutationResolver) Supervisor(ctx context.Context, obj *model.TeacherMutation) (*model.SupervisorMutation, error) {
	r.Resolver.RbacRoleDynamic(ctx, "supervisor")
	return &model.SupervisorMutation{}, nil
}

// Council is the resolver for the council field.
func (r *teacherMutationResolver) Council(ctx context.Context, obj *model.TeacherMutation) (*model.CouncilMemberMutation, error) {
	r.Resolver.RbacRoleDynamic(ctx, "council")
	return &model.CouncilMemberMutation{}, nil
}

// Reviewer is the resolver for the reviewer field.
func (r *teacherMutationResolver) Reviewer(ctx context.Context, obj *model.TeacherMutation) (*model.ReviewerMutation, error) {
	r.Resolver.RbacRoleDynamic(ctx, "reviewer")
	return &model.ReviewerMutation{}, nil
}

// ============================================
// SUPERVISOR MUTATION NAMESPACE
// ============================================

// CreateTopic is the resolver for the createTopic field.
func (r *supervisorMutationResolver) CreateTopic(ctx context.Context, obj *model.SupervisorMutation, input model.CreateTopicInput) (*model.Topic, error) {
	return r.Ctrl.CreateTopicForSuperVisor(ctx, input)
}

// CreateTopicCouncil is the resolver for the createTopicCouncil field.
func (r *supervisorMutationResolver) CreateTopicCouncil(ctx context.Context, obj *model.SupervisorMutation, input model.CreateTopicCouncilInput) (*model.TopicCouncil, error) {
	return r.Ctrl.CreateTopicCouncilForSuperVisor(ctx, input)
}

// GradeMidterm is the resolver for the gradeMidterm field.
func (r *supervisorMutationResolver) GradeMidterm(ctx context.Context, obj *model.SupervisorMutation, enrollmentID string, input model.GradeMidtermInput) (*model.Midterm, error) {
	return r.Ctrl.GradeMidterm(ctx, enrollmentID, input)
}

// FeedbackMidterm is the resolver for the feedbackMidterm field.
func (r *supervisorMutationResolver) FeedbackMidterm(ctx context.Context, obj *model.SupervisorMutation, midtermID string, feedback string) (*model.Midterm, error) {
	return r.Ctrl.FeedbackMidterm(ctx, midtermID, feedback)
}

// GradeFinal is the resolver for the gradeFinal field.
func (r *supervisorMutationResolver) GradeFinal(ctx context.Context, obj *model.SupervisorMutation, enrollmentID string, input model.GradeFinalInput) (*model.Final, error) {
	return r.Ctrl.GradeFinal(ctx, enrollmentID, input)
}

// FeedbackFinal is the resolver for the feedbackFinal field.
func (r *supervisorMutationResolver) FeedbackFinal(ctx context.Context, obj *model.SupervisorMutation, finalID string, notes string) (*model.Final, error) {
	return r.Ctrl.FeedbackFinal(ctx, finalID, notes)
}

// ApproveMidtermFile is the resolver for the approveMidtermFile field.
func (r *supervisorMutationResolver) ApproveMidtermFile(ctx context.Context, obj *model.SupervisorMutation, fileID string) (*model.File, error) {
	return r.Ctrl.ApproveMidtermFile(ctx, fileID)
}

// RejectMidtermFile is the resolver for the rejectMidtermFile field.
func (r *supervisorMutationResolver) RejectMidtermFile(ctx context.Context, obj *model.SupervisorMutation, fileID string, reason *string) (*model.File, error) {
	return r.Ctrl.RejectMidtermFile(ctx, fileID, reason)
}

// ApproveFinalFile is the resolver for the approveFinalFile field.
func (r *supervisorMutationResolver) ApproveFinalFile(ctx context.Context, obj *model.SupervisorMutation, fileID string) (*model.File, error) {
	return r.Ctrl.ApproveFinalFile(ctx, fileID)
}

// RejectFinalFile is the resolver for the rejectFinalFile field.
func (r *supervisorMutationResolver) RejectFinalFile(ctx context.Context, obj *model.SupervisorMutation, fileID string, reason *string) (*model.File, error) {
	return r.Ctrl.RejectFinalFile(ctx, fileID, reason)
}

// ============================================
// COUNCIL MEMBER MUTATION NAMESPACE
// ============================================

// CreateGradeDefence is the resolver for the createGradeDefence field.
func (r *councilMemberMutationResolver) CreateGradeDefence(ctx context.Context, obj *model.CouncilMemberMutation, input model.CreateGradeDefenceInput) (*model.GradeDefence, error) {
	return r.Ctrl.CreateGradeDefence(ctx, input)
}

// UpdateGradeDefence is the resolver for the updateGradeDefence field.
func (r *councilMemberMutationResolver) UpdateGradeDefence(ctx context.Context, obj *model.CouncilMemberMutation, id string, input model.UpdateGradeDefenceInput) (*model.GradeDefence, error) {
	return r.Ctrl.UpdateGradeDefence(ctx, id, input)
}

// AddCriterion is the resolver for the addCriterion field.
func (r *councilMemberMutationResolver) AddCriterion(ctx context.Context, obj *model.CouncilMemberMutation, input model.CreateGradeDefenceCriterionInput) (*model.GradeDefenceCriterion, error) {
	return r.Ctrl.AddGradeDefenceCriterion(ctx, input)
}

// UpdateCriterion is the resolver for the updateCriterion field.
func (r *councilMemberMutationResolver) UpdateCriterion(ctx context.Context, obj *model.CouncilMemberMutation, id string, input model.UpdateGradeDefenceCriterionInput) (*model.GradeDefenceCriterion, error) {
	return r.Ctrl.UpdateGradeDefenceCriterion(ctx, id, input)
}

// DeleteCriterion is the resolver for the deleteCriterion field.
func (r *councilMemberMutationResolver) DeleteCriterion(ctx context.Context, obj *model.CouncilMemberMutation, id string) (bool, error) {
	return r.Ctrl.DeleteGradeDefenceCriterion(ctx, id)
}

// ============================================
// REVIEWER MUTATION NAMESPACE
// ============================================

// UpdateGradeReview is the resolver for the updateGradeReview field.
func (r *reviewerMutationResolver) UpdateGradeReview(ctx context.Context, obj *model.ReviewerMutation, id string, input model.UpdateGradeReviewInput) (*model.GradeReview, error) {
	return r.Ctrl.UpdateGradeReview(ctx, id, input)
}

// CompleteGradeReview is the resolver for the completeGradeReview field.
func (r *reviewerMutationResolver) CompleteGradeReview(ctx context.Context, obj *model.ReviewerMutation, id string) (*model.GradeReview, error) {
	return r.Ctrl.CompleteGradeReview(ctx, id)
}

// ============================================
// AFFAIR MUTATION NAMESPACE - Full access
// ============================================

// CreateTeacher is the resolver for the createTeacher field.
func (r *affairMutationResolver) CreateTeacher(ctx context.Context, obj *model.AffairMutation, input model.CreateTeacherInput) (*model.Teacher, error) {
	return r.Ctrl.CreateTeacher(ctx, input)
}

// UpdateTeacher is the resolver for the updateTeacher field.
func (r *affairMutationResolver) UpdateTeacher(ctx context.Context, obj *model.AffairMutation, id string, input model.UpdateTeacherInput) (*model.Teacher, error) {
	return r.Ctrl.UpdateTeacher(ctx, id, input)
}

// DeleteTeacher is the resolver for the deleteTeacher field.
func (r *affairMutationResolver) DeleteTeacher(ctx context.Context, obj *model.AffairMutation, id string) (bool, error) {
	return r.Ctrl.DeleteTeacher(ctx, id)
}

// CreateStudent is the resolver for the createStudent field.
func (r *affairMutationResolver) CreateStudent(ctx context.Context, obj *model.AffairMutation, input model.CreateStudentInput) (*model.Student, error) {
	return r.Ctrl.CreateStudent(ctx, input)
}

// UpdateStudent is the resolver for the updateStudent field.
func (r *affairMutationResolver) UpdateStudent(ctx context.Context, obj *model.AffairMutation, id string, input model.UpdateStudentInput) (*model.Student, error) {
	return r.Ctrl.UpdateStudent(ctx, id, input)
}

// DeleteStudent is the resolver for the deleteStudent field.
func (r *affairMutationResolver) DeleteStudent(ctx context.Context, obj *model.AffairMutation, id string) (bool, error) {
	return r.Ctrl.DeleteStudent(ctx, id)
}

// CreateSemester is the resolver for the createSemester field.
func (r *affairMutationResolver) CreateSemester(ctx context.Context, obj *model.AffairMutation, input model.CreateSemesterInput) (*model.Semester, error) {
	return r.Ctrl.CreateSemester(ctx, input)
}

// UpdateSemester is the resolver for the updateSemester field.
func (r *affairMutationResolver) UpdateSemester(ctx context.Context, obj *model.AffairMutation, id string, input model.UpdateSemesterInput) (*model.Semester, error) {
	return r.Ctrl.UpdateSemester(ctx, id, input)
}

// DeleteSemester is the resolver for the deleteSemester field.
func (r *affairMutationResolver) DeleteSemester(ctx context.Context, obj *model.AffairMutation, id string) (bool, error) {
	return r.Ctrl.DeleteSemester(ctx, id)
}

// CreateMajor is the resolver for the createMajor field.
func (r *affairMutationResolver) CreateMajor(ctx context.Context, obj *model.AffairMutation, input model.CreateMajorInput) (*model.Major, error) {
	return r.Ctrl.CreateMajor(ctx, input)
}

// UpdateMajor is the resolver for the updateMajor field.
func (r *affairMutationResolver) UpdateMajor(ctx context.Context, obj *model.AffairMutation, id string, input model.UpdateMajorInput) (*model.Major, error) {
	return r.Ctrl.UpdateMajor(ctx, id, input)
}

// DeleteMajor is the resolver for the deleteMajor field.
func (r *affairMutationResolver) DeleteMajor(ctx context.Context, obj *model.AffairMutation, id string) (bool, error) {
	return r.Ctrl.DeleteMajor(ctx, id)
}

// CreateFaculty is the resolver for the createFaculty field.
func (r *affairMutationResolver) CreateFaculty(ctx context.Context, obj *model.AffairMutation, input model.CreateFacultyInput) (*model.Faculty, error) {
	return r.Ctrl.CreateFaculty(ctx, input)
}

// UpdateFaculty is the resolver for the updateFaculty field.
func (r *affairMutationResolver) UpdateFaculty(ctx context.Context, obj *model.AffairMutation, id string, input model.UpdateFacultyInput) (*model.Faculty, error) {
	return r.Ctrl.UpdateFaculty(ctx, id, input)
}

// DeleteFaculty is the resolver for the deleteFaculty field.
func (r *affairMutationResolver) DeleteFaculty(ctx context.Context, obj *model.AffairMutation, id string) (bool, error) {
	return r.Ctrl.DeleteFaculty(ctx, id)
}

// ApproveCouncil is the resolver for the approveCouncil field.
func (r *affairMutationResolver) ApproveCouncil(ctx context.Context, obj *model.AffairMutation, id string, timeStart time.Time) (*model.Council, error) {
	return r.Ctrl.ApproveCouncil(ctx, id, timeStart)
}

// UpdateCouncil is the resolver for the updateCouncil field.
func (r *affairMutationResolver) UpdateCouncil(ctx context.Context, obj *model.AffairMutation, id string, input model.UpdateCouncilInput) (*model.Council, error) {
	return r.Ctrl.UpdateCouncil(ctx, id, input)
}

// DeleteCouncil is the resolver for the deleteCouncil field.
func (r *affairMutationResolver) DeleteCouncil(ctx context.Context, obj *model.AffairMutation, id string) (bool, error) {
	return r.Ctrl.DeleteCouncil(ctx, id)
}

// ApproveTopic is the resolver for the approveTopic field.
func (r *affairMutationResolver) ApproveTopic(ctx context.Context, obj *model.AffairMutation, id string) (*model.Topic, error) {
	return r.Ctrl.ApproveTopic(ctx, id)
}

// RejectTopic is the resolver for the rejectTopic field.
func (r *affairMutationResolver) RejectTopic(ctx context.Context, obj *model.AffairMutation, id string, reason *string) (*model.Topic, error) {
	return r.Ctrl.RejectTopic(ctx, id, reason)
}

// UpdateTopic is the resolver for the updateTopic field.
func (r *affairMutationResolver) UpdateTopic(ctx context.Context, obj *model.AffairMutation, id string, input model.UpdateTopicInput) (*model.Topic, error) {
	return r.Ctrl.UpdateTopic(ctx, id, input)
}

// DeleteTopic is the resolver for the deleteTopic field.
func (r *affairMutationResolver) DeleteTopic(ctx context.Context, obj *model.AffairMutation, id string) (bool, error) {
	return r.Ctrl.DeleteTopic(ctx, id)
}

// ============================================
// DEPARTMENT MUTATION NAMESPACE
// ============================================

// CreateCouncil is the resolver for the createCouncil field.
func (r *departmentMutationResolver) CreateCouncil(ctx context.Context, obj *model.DepartmentMutation, input model.CreateCouncilInput) (*model.Council, error) {
	return r.Ctrl.CreateCouncil(ctx, input)
}

// UpdateCouncil is the resolver for the updateCouncil field.
func (r *departmentMutationResolver) UpdateCouncil(ctx context.Context, obj *model.DepartmentMutation, id string, input model.UpdateCouncilInput) (*model.Council, error) {
	return r.Ctrl.UpdateDepartmentCouncil(ctx, id, input)
}

// AddDefence is the resolver for the addDefence field.
func (r *departmentMutationResolver) AddDefence(ctx context.Context, obj *model.DepartmentMutation, input model.CreateDefenceInput) (*model.Defence, error) {
	return r.Ctrl.AddDefenceToCouncil(ctx, input)
}

// RemoveDefence is the resolver for the removeDefence field.
func (r *departmentMutationResolver) RemoveDefence(ctx context.Context, obj *model.DepartmentMutation, id string) (bool, error) {
	return r.Ctrl.RemoveDefenceFromCouncil(ctx, id)
}

// ApproveTopicStage1 is the resolver for the approveTopicStage1 field.
func (r *departmentMutationResolver) ApproveTopicStage1(ctx context.Context, obj *model.DepartmentMutation, id string) (*model.Topic, error) {
	return r.Ctrl.ApproveTopicStage1(ctx, id)
}

// RejectTopicStage1 is the resolver for the rejectTopicStage1 field.
func (r *departmentMutationResolver) RejectTopicStage1(ctx context.Context, obj *model.DepartmentMutation, id string, reason *string) (*model.Topic, error) {
	return r.Ctrl.RejectTopicStage1(ctx, id, reason)
}

// AssignTopicToCouncil is the resolver for the assignTopicToCouncil field.
func (r *departmentMutationResolver) AssignTopicToCouncil(ctx context.Context, obj *model.DepartmentMutation, topicCouncilID string, councilID string) (*model.TopicCouncil, error) {
	return r.Ctrl.AssignTopicToCouncil(ctx, topicCouncilID, councilID)
}

// RemoveTopicFromCouncil is the resolver for the removeTopicFromCouncil field.
func (r *departmentMutationResolver) RemoveTopicFromCouncil(ctx context.Context, obj *model.DepartmentMutation, topicCouncilID string, councilID string) (bool, error) {
	return r.Ctrl.RemoveTopicFromCouncil(ctx, topicCouncilID, councilID)
}

// ============================================
// RESOLVER IMPLEMENTATIONS
// ============================================

// AffairMutation returns generated.AffairMutationResolver implementation.
func (r *Resolver) AffairMutation() generated.AffairMutationResolver {
	return &affairMutationResolver{r}
}

// CouncilMemberMutation returns generated.CouncilMemberMutationResolver implementation.
func (r *Resolver) CouncilMemberMutation() generated.CouncilMemberMutationResolver {
	return &councilMemberMutationResolver{r}
}

// DepartmentMutation returns generated.DepartmentMutationResolver implementation.
func (r *Resolver) DepartmentMutation() generated.DepartmentMutationResolver {
	return &departmentMutationResolver{r}
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// ReviewerMutation returns generated.ReviewerMutationResolver implementation.
func (r *Resolver) ReviewerMutation() generated.ReviewerMutationResolver {
	return &reviewerMutationResolver{r}
}

// StudentMutation returns generated.StudentMutationResolver implementation.
func (r *Resolver) StudentMutation() generated.StudentMutationResolver {
	return &studentMutationResolver{r}
}

// SupervisorMutation returns generated.SupervisorMutationResolver implementation.
func (r *Resolver) SupervisorMutation() generated.SupervisorMutationResolver {
	return &supervisorMutationResolver{r}
}

// TeacherMutation returns generated.TeacherMutationResolver implementation.
func (r *Resolver) TeacherMutation() generated.TeacherMutationResolver {
	return &teacherMutationResolver{r}
}

type affairMutationResolver struct{ *Resolver }
type councilMemberMutationResolver struct{ *Resolver }
type departmentMutationResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type reviewerMutationResolver struct{ *Resolver }
type studentMutationResolver struct{ *Resolver }
type supervisorMutationResolver struct{ *Resolver }
type teacherMutationResolver struct{ *Resolver }
