package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"thaily/src/server/graph/generated"
	"thaily/src/server/graph/model"
)

// Teachers is the resolver for the teachers field.
func (r *affairQueryResolver) Teachers(ctx context.Context, obj *model.AffairQuery, search model.SearchRequestInput) (*model.TeacherListResponse, error) {
	return r.Ctrl.GetListTeachers(ctx, search)
}

// TeacherDetail is the resolver for the teacherDetail field.
func (r *affairQueryResolver) TeacherDetail(ctx context.Context, obj *model.AffairQuery, id string) (*model.Teacher, error) {
	return r.Ctrl.GetTeacherById(ctx, id)
}

// Students is the resolver for the students field.
func (r *affairQueryResolver) Students(ctx context.Context, obj *model.AffairQuery, search model.SearchRequestInput) (*model.StudentListResponse, error) {
	return r.Ctrl.GetListStudents(ctx, search)
}

// StudentDetail is the resolver for the studentDetail field.
func (r *affairQueryResolver) StudentDetail(ctx context.Context, obj *model.AffairQuery, id string) (*model.Student, error) {
	return r.Ctrl.GetStudentById(ctx, id)
}

// Semesters is the resolver for the semesters field.
func (r *affairQueryResolver) Semesters(ctx context.Context, obj *model.AffairQuery, search model.SearchRequestInput) (*model.SemesterListResponse, error) {
	return r.Ctrl.GetAllSemesters(ctx, search)
}

// SemesterDetail is the resolver for the semesterDetail field.
func (r *affairQueryResolver) SemesterDetail(ctx context.Context, obj *model.AffairQuery, id string) (*model.Semester, error) {
	return r.Ctrl.GetSemesterById(ctx, id)
}

// Majors is the resolver for the majors field.
func (r *affairQueryResolver) Majors(ctx context.Context, obj *model.AffairQuery, search model.SearchRequestInput) (*model.MajorListResponse, error) {
	return r.Ctrl.GetAllMajors(ctx, search)
}

// MajorDetail is the resolver for the majorDetail field.
func (r *affairQueryResolver) MajorDetail(ctx context.Context, obj *model.AffairQuery, id string) (*model.Major, error) {
	return r.Ctrl.GetMajorById(ctx, id)
}

// Faculties is the resolver for the faculties field.
func (r *affairQueryResolver) Faculties(ctx context.Context, obj *model.AffairQuery, search model.SearchRequestInput) (*model.FacultyListResponse, error) {
	return r.Ctrl.GetAllFaculties(ctx, search)
}

// FacultyDetail is the resolver for the facultyDetail field.
func (r *affairQueryResolver) FacultyDetail(ctx context.Context, obj *model.AffairQuery, id string) (*model.Faculty, error) {
	return r.Ctrl.GetFacultyById(ctx, id)
}

// Topics is the resolver for the topics field.
func (r *affairQueryResolver) Topics(ctx context.Context, obj *model.AffairQuery, search model.SearchRequestInput) (*model.TopicListResponse, error) {
	return r.Ctrl.GetAllTopics(ctx, search)
}

// TopicDetail is the resolver for the topicDetail field.
func (r *affairQueryResolver) TopicDetail(ctx context.Context, obj *model.AffairQuery, id string) (*model.Topic, error) {
	return r.Ctrl.GetTopicById(ctx, id)
}

// Enrollments is the resolver for the enrollments field.
func (r *affairQueryResolver) Enrollments(ctx context.Context, obj *model.AffairQuery, search model.SearchRequestInput) (*model.EnrollmentListResponse, error) {
	return r.Ctrl.GetAllEnrollments(ctx, search)
}

// EnrollmentDetail is the resolver for the enrollmentDetail field.
func (r *affairQueryResolver) EnrollmentDetail(ctx context.Context, obj *model.AffairQuery, id string) (*model.Enrollment, error) {
	return r.Ctrl.GetEnrollmentById(ctx, id)
}

// Councils is the resolver for the councils field.
func (r *affairQueryResolver) Councils(ctx context.Context, obj *model.AffairQuery, search model.SearchRequestInput) (*model.CouncilListResponse, error) {
	return r.Ctrl.GetAllCouncils(ctx, search)
}

// CouncilDetail is the resolver for the councilDetail field.
func (r *affairQueryResolver) CouncilDetail(ctx context.Context, obj *model.AffairQuery, id string) (*model.Council, error) {
	return r.Ctrl.GetCouncilById(ctx, id)
}

// DefencesByCouncil is the resolver for the defencesByCouncil field.
func (r *affairQueryResolver) DefencesByCouncil(ctx context.Context, obj *model.AffairQuery, councilID string) (*model.DefenceListResponse, error) {
	return r.Ctrl.GetDefencesByCouncil(ctx, councilID)
}

// GradeDefences is the resolver for the gradeDefences field.
func (r *affairQueryResolver) GradeDefences(ctx context.Context, obj *model.AffairQuery, search model.SearchRequestInput) (*model.GradeDefenceListResponse, error) {
	return r.Ctrl.GetAllGradeDefences(ctx, search)
}

// Defences is the resolver for the defences field.
func (r *councilMemberQueryResolver) Defences(ctx context.Context, obj *model.CouncilMemberQuery, search *model.SearchRequestInput) (*model.DefenceListResponse, error) {
	return r.Ctrl.GetMyDefences(ctx, search)
}

// Teachers is the resolver for the teachers field.
func (r *departmentQueryResolver) Teachers(ctx context.Context, obj *model.DepartmentQuery, search model.SearchRequestInput) (*model.TeacherListResponse, error) {
	return r.Ctrl.GetDepartmentTeachers(ctx, search)
}

// Students is the resolver for the students field.
func (r *departmentQueryResolver) Students(ctx context.Context, obj *model.DepartmentQuery, search model.SearchRequestInput) (*model.StudentListResponse, error) {
	return r.Ctrl.GetDepartmentStudents(ctx, search)
}

// Semesters is the resolver for the semesters field.
func (r *departmentQueryResolver) Semesters(ctx context.Context, obj *model.DepartmentQuery, search model.SearchRequestInput) (*model.SemesterListResponse, error) {
	return r.Ctrl.GetDepartmentSemesters(ctx, search)
}

// Majors is the resolver for the majors field.
func (r *departmentQueryResolver) Majors(ctx context.Context, obj *model.DepartmentQuery, search model.SearchRequestInput) (*model.MajorListResponse, error) {
	return r.Ctrl.GetDepartmentMajors(ctx, search)
}

// Faculties is the resolver for the faculties field.
func (r *departmentQueryResolver) Faculties(ctx context.Context, obj *model.DepartmentQuery, search model.SearchRequestInput) (*model.FacultyListResponse, error) {
	return r.Ctrl.GetDepartmentFaculties(ctx, search)
}

// Topics is the resolver for the topics field.
func (r *departmentQueryResolver) Topics(ctx context.Context, obj *model.DepartmentQuery, search model.SearchRequestInput) (*model.TopicListResponse, error) {
	return r.Ctrl.GetDepartmentTopics(ctx, search)
}

// Enrollments is the resolver for the enrollments field.
func (r *departmentQueryResolver) Enrollments(ctx context.Context, obj *model.DepartmentQuery, search model.SearchRequestInput) (*model.EnrollmentListResponse, error) {
	return r.Ctrl.GetDepartmentEnrollments(ctx, search)
}

// Councils is the resolver for the councils field.
func (r *departmentQueryResolver) Councils(ctx context.Context, obj *model.DepartmentQuery, search model.SearchRequestInput) (*model.CouncilListResponse, error) {
	return r.Ctrl.GetDepartmentCouncils(ctx, search)
}

// GradeDefences is the resolver for the gradeDefences field.
func (r *departmentQueryResolver) GradeDefences(ctx context.Context, obj *model.DepartmentQuery, search model.SearchRequestInput) (*model.GradeDefenceListResponse, error) {
	return r.Ctrl.GetDepartmentGradeDefences(ctx, search)
}

// Student is the resolver for the student field.
func (r *queryResolver) Student(ctx context.Context) (*model.StudentQuery, error) {
	r.Resolver.RbacRoleDynamic(ctx, "student")
	return &model.StudentQuery{}, nil
}

// Teacher is the resolver for the teacher field.
func (r *queryResolver) Teacher(ctx context.Context) (*model.TeacherQuery, error) {
	r.Resolver.RbacRoleDynamic(ctx, "teacher")
	return &model.TeacherQuery{}, nil
}

// Affair is the resolver for the affair field.
func (r *queryResolver) Affair(ctx context.Context) (*model.AffairQuery, error) {
	r.Resolver.RbacRoleDynamic(ctx, "affair")
	return &model.AffairQuery{}, nil
}

// Department is the resolver for the department field.
func (r *queryResolver) Department(ctx context.Context) (*model.DepartmentQuery, error) {
	r.Resolver.RbacRoleDynamic(ctx, "department")
	return &model.DepartmentQuery{}, nil
}

// Me is the resolver for the me field.
func (r *studentQueryResolver) Me(ctx context.Context, obj *model.StudentQuery) (*model.Student, error) {
	return r.Ctrl.GetStudentByRequest(ctx)
}

// Enrollments is the resolver for the enrollments field.
func (r *studentQueryResolver) Enrollments(ctx context.Context, obj *model.StudentQuery, search *model.SearchRequestInput) (*model.EnrollmentListResponse, error) {
	return r.Ctrl.GetEnrollmentsForStudent(ctx, search)
}

// Semesters is the resolver for the semesters field.
func (r *studentQueryResolver) Semesters(ctx context.Context, obj *model.StudentQuery, search *model.SearchRequestInput) (*model.SemesterListResponse, error) {
	return r.Ctrl.GetMySemesters(ctx, search)
}

// TopicCouncils is the resolver for the topicCouncils field.
func (r *supervisorQueryResolver) TopicCouncils(ctx context.Context, obj *model.SupervisorQuery, search *model.SearchRequestInput) (*model.TopicCouncilListResponse, error) {
	return r.Ctrl.GetSupervisedTopicCouncils(ctx, search)
}

// Me is the resolver for the me field.
func (r *teacherQueryResolver) Me(ctx context.Context, obj *model.TeacherQuery) (*model.Teacher, error) {
	return r.Ctrl.GetTeacherByRequest(ctx)
}

// Supervisor is the resolver for the supervisor field.
func (r *teacherQueryResolver) Supervisor(ctx context.Context, obj *model.TeacherQuery) (*model.SupervisorQuery, error) {
	r.Resolver.RbacRoleDynamic(ctx, "supervisor")
	return &model.SupervisorQuery{}, nil
}

// Council is the resolver for the council field.
func (r *teacherQueryResolver) Council(ctx context.Context, obj *model.TeacherQuery) (*model.CouncilMemberQuery, error) {
	r.Resolver.RbacRoleDynamic(ctx, "council")
	return &model.CouncilMemberQuery{}, nil
}

// AffairQuery returns generated.AffairQueryResolver implementation.
func (r *Resolver) AffairQuery() generated.AffairQueryResolver { return &affairQueryResolver{r} }

// CouncilMemberQuery returns generated.CouncilMemberQueryResolver implementation.
func (r *Resolver) CouncilMemberQuery() generated.CouncilMemberQueryResolver {
	return &councilMemberQueryResolver{r}
}

// DepartmentQuery returns generated.DepartmentQueryResolver implementation.
func (r *Resolver) DepartmentQuery() generated.DepartmentQueryResolver {
	return &departmentQueryResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// StudentQuery returns generated.StudentQueryResolver implementation.
func (r *Resolver) StudentQuery() generated.StudentQueryResolver { return &studentQueryResolver{r} }

// SupervisorQuery returns generated.SupervisorQueryResolver implementation.
func (r *Resolver) SupervisorQuery() generated.SupervisorQueryResolver {
	return &supervisorQueryResolver{r}
}

// TeacherQuery returns generated.TeacherQueryResolver implementation.
func (r *Resolver) TeacherQuery() generated.TeacherQueryResolver { return &teacherQueryResolver{r} }

type affairQueryResolver struct{ *Resolver }
type councilMemberQueryResolver struct{ *Resolver }
type departmentQueryResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type studentQueryResolver struct{ *Resolver }
type supervisorQueryResolver struct{ *Resolver }
type teacherQueryResolver struct{ *Resolver }
