package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"thaily/src/server/graph/dataloader"
	"thaily/src/server/graph/generated"
	"thaily/src/server/graph/model"
)

// Teacher is the resolver for the teacher field.
func (r *roleSystemResolver) Teacher(ctx context.Context, obj *model.RoleSystem) (*model.Teacher, error) {
	if obj.TeacherCode == nil {
		return nil, nil
	}

	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.TeacherById != nil {
		teacher, err := loaders.TeacherById.Load(ctx, *obj.TeacherCode)
		if err != nil {
			return nil, err
		}
		return teacher, nil
	}

	return r.Ctrl.GetTeacherById(ctx, *obj.TeacherCode)
}

// Semester is the resolver for the semester field.
func (r *roleSystemResolver) Semester(ctx context.Context, obj *model.RoleSystem) (*model.Semester, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.SemesterById != nil {
		return loaders.SemesterById.Load(ctx, obj.SemesterCode)
	}
	return r.Ctrl.GetSemesterById(ctx, obj.SemesterCode)
}

// RoleSystem returns generated.RoleSystemResolver implementation.
func (r *Resolver) RoleSystem() generated.RoleSystemResolver { return &roleSystemResolver{r} }

type roleSystemResolver struct{ *Resolver }
