package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"thaily/src/server/graph/dataloader"
	"thaily/src/server/graph/generated"
	"thaily/src/server/graph/model"
)

// UploadMidtermFile is the resolver for the uploadMidtermFile field.
func (r *mutationResolver) UploadMidtermFile(ctx context.Context, input model.UploadFileInput) (*model.File, error) {
	panic(fmt.Errorf("not implemented: UploadMidtermFile - uploadMidtermFile"))
}

// UploadFinalFile is the resolver for the uploadFinalFile field.
func (r *mutationResolver) UploadFinalFile(ctx context.Context, input model.UploadFileInput) (*model.File, error) {
	panic(fmt.Errorf("not implemented: UploadFinalFile - uploadFinalFile"))
}

// GetMyProfile is the resolver for the getMyProfile field.
func (r *queryResolver) GetMyProfile(ctx context.Context) (*model.Student, error) {
	return r.Ctrl.GetStudentByRequest(ctx)
}

// GetMyEnrollments is the resolver for the getMyEnrollments field.
func (r *queryResolver) GetMyEnrollments(ctx context.Context, search *model.SearchRequestInput) (*model.StudentEnrollmentListResponse, error) {
	return r.Ctrl.GetEnrollmentsForStudent(ctx, search)
}

// GetMySemesters is the resolver for the getMySemesters field.
func (r *queryResolver) GetMySemesters(ctx context.Context, search *model.SearchRequestInput) (*model.SemesterListResponse, error) {
	return r.Ctrl.GetMySemesters(ctx, search)
}

// Major is the resolver for the major field.
func (r *studentCouncilResolver) Major(ctx context.Context, obj *model.StudentCouncil) (*model.MajorInfo, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.MajorInfoById != nil {
		major, err := loaders.MajorInfoById.Load(ctx, obj.MajorCode)
		if err != nil {
			return nil, err
		}
		return major, nil
	}
	major, err := r.Ctrl.GetMajorInfo(ctx, obj.MajorCode)
	if err != nil {
		return nil, err
	}
	return major, nil
}

// Semester is the resolver for the semester field.
func (r *studentCouncilResolver) Semester(ctx context.Context, obj *model.StudentCouncil) (*model.SemesterInfo, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.SemesterInfoById != nil {
		semester, err := loaders.SemesterInfoById.Load(ctx, obj.SemesterCode)
		if err != nil {
			return nil, err
		}
		return semester, nil
	}
	semester, err := r.Ctrl.GetSemesterInfo(ctx, obj.MajorCode)
	if err != nil {
		return nil, err
	}
	return semester, nil
}

// Defences is the resolver for the defences field.
func (r *studentCouncilResolver) Defences(ctx context.Context, obj *model.StudentCouncil) ([]*model.StudentDefenceInfo, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.DefenceInfoByCouncilId != nil {
		defence, err := loaders.DefenceInfoByCouncilId.Load(ctx, obj.ID)
		if err != nil {
			return nil, err
		}
		return defence, nil
	}
	defence, err := r.Ctrl.GetDefenceInfoByCouncilId(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return []*model.StudentDefenceInfo{defence}, nil
}

// Teacher is the resolver for the teacher field.
func (r *studentDefenceInfoResolver) Teacher(ctx context.Context, obj *model.StudentDefenceInfo) (*model.StudentTeacherInfo, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.TeacherInfoById != nil {
		teacher, err := loaders.TeacherInfoById.Load(ctx, obj.TeacherCode)
		if err != nil {
			return nil, err
		}
		return teacher, nil
	}
	teacher, err := r.Ctrl.GetTeacherInfoById(ctx, obj.TeacherCode)
	if err != nil {
		return nil, err
	}
	return teacher, nil
}

// TopicCouncil is the resolver for the topicCouncil field.
func (r *studentEnrollmentResolver) TopicCouncil(ctx context.Context, obj *model.StudentEnrollment) (*model.StudentTopicCouncil, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.TopicCouncilInfoById != nil {
		topicCouncil, err := loaders.TopicCouncilInfoById.Load(ctx, obj.TopicCouncilCode)
		if err != nil {
			return nil, err
		}
		return topicCouncil, nil
	}
	topicCouncil, err := r.Ctrl.GetTopicCouncilForStudent(ctx, obj.StudentCode)
	if err != nil {
		return nil, err
	}
	return topicCouncil, nil
}

// Midterm is the resolver for the midterm field.
func (r *studentEnrollmentResolver) Midterm(ctx context.Context, obj *model.StudentEnrollment) (*model.Midterm, error) {
	if obj.MidtermCode == nil {
		return nil, nil
	}
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.MidtermByID != nil {
		midterm, err := loaders.MidtermByID.Load(ctx, *obj.MidtermCode)
		if err != nil {
			return nil, err
		}
		return midterm, nil
	}
	midterm, err := r.Ctrl.GetMidtermById(ctx, *obj.MidtermCode)
	if err != nil {
		return nil, err
	}
	return midterm, nil
}

// Final is the resolver for the final field.
func (r *studentEnrollmentResolver) Final(ctx context.Context, obj *model.StudentEnrollment) (*model.Final, error) {
	if obj.FinalCode == nil {
		return nil, nil
	}
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.FinalByID != nil {
		final, err := loaders.FinalByID.Load(ctx, *obj.FinalCode)
		if err != nil {
			return nil, err
		}
		return final, nil
	}
	final, err := r.Ctrl.GetFinalById(ctx, *obj.FinalCode)
	if err != nil {
		return nil, err
	}
	return final, nil
}

// GradeReview is the resolver for the gradeReview field.
func (r *studentEnrollmentResolver) GradeReview(ctx context.Context, obj *model.StudentEnrollment) (*model.GradeReview, error) {
	if obj.GradeReviewCode == nil {
		return nil, nil
	}
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.GradeViewById != nil {
		gradeView, err := loaders.GradeViewById.Load(ctx, *obj.GradeReviewCode)
		if err != nil {
			return nil, err
		}
		return gradeView, nil
	}
	gradeView, err := r.Ctrl.GetGradeViewById(ctx, *obj.GradeReviewCode)
	if err != nil {
		return nil, err
	}
	return gradeView, nil
}

// GradeDefences is the resolver for the gradeDefences field.
func (r *studentEnrollmentResolver) GradeDefences(ctx context.Context, obj *model.StudentEnrollment) ([]*model.StudentGradeDefence, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.GradeDefencesInfoByEnrollmentId != nil {
		gradeDefences, err := loaders.GradeDefencesInfoByEnrollmentId.Load(ctx, obj.ID)
		if err != nil {
			return nil, err
		}
		return gradeDefences, nil
	}
	gradeDefence, err := r.Ctrl.GetGradeDefenceInfoByEnrollmentCode(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return gradeDefence, nil
}

// Criteria is the resolver for the criteria field.
func (r *studentGradeDefenceResolver) Criteria(ctx context.Context, obj *model.StudentGradeDefence) ([]*model.GradeDefenceCriterion, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.GradeDefenceCriteriaByDefenceId != nil {
		criteria, err := loaders.GradeDefenceCriteriaByDefenceId.Load(ctx, obj.ID)
		if err != nil {
			return nil, err
		}
		return criteria, nil
	}
	criterion, err := r.Ctrl.GetGradeDefenceCriterionByDefenceCode(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return criterion, nil
}

// Defence is the resolver for the defence field.
func (r *studentGradeDefenceResolver) Defence(ctx context.Context, obj *model.StudentGradeDefence) (*model.StudentDefenceInfo, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.DefenceInfoById != nil {
		defences, err := loaders.DefenceInfoById.Load(ctx, obj.DefenceCode)
		if err != nil {
			return nil, err
		}
		return defences, nil
	}
	defence, err := r.Ctrl.GetDefenceInfoById(ctx, obj.DefenceCode)
	if err != nil {
		return nil, err
	}
	return defence, nil
}

// Major is the resolver for the major field.
func (r *studentTopicResolver) Major(ctx context.Context, obj *model.StudentTopic) (*model.MajorInfo, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.MajorInfoById != nil {
		major, err := loaders.MajorInfoById.Load(ctx, obj.MajorCode)
		if err != nil {
			return nil, err
		}
		return major, nil
	}
	major, err := r.Ctrl.GetMajorInfo(ctx, obj.MajorCode)
	if err != nil {
		return nil, err
	}
	return major, nil
}

// Semester is the resolver for the semester field.
func (r *studentTopicResolver) Semester(ctx context.Context, obj *model.StudentTopic) (*model.SemesterInfo, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.SemesterInfoById != nil {
		semester, err := loaders.SemesterInfoById.Load(ctx, obj.SemesterCode)
		if err != nil {
			return nil, err
		}
		return semester, nil
	}
	semester, err := r.Ctrl.GetSemesterInfo(ctx, obj.MajorCode)
	if err != nil {
		return nil, err
	}
	return semester, nil
}

// Files is the resolver for the files field.
func (r *studentTopicResolver) Files(ctx context.Context, obj *model.StudentTopic) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: Files - files"))
}

// Topic is the resolver for the topic field.
func (r *studentTopicCouncilResolver) Topic(ctx context.Context, obj *model.StudentTopicCouncil) (*model.StudentTopic, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.TopicForStudentByID != nil {
		topics, err := loaders.TopicForStudentByID.Load(ctx, obj.TopicCode)
		if err != nil {
			return nil, err
		}
		return topics, nil
	}
	topic, err := r.Ctrl.GetTopicForStudent(ctx, obj.TopicCode)
	if err != nil {
		return nil, err
	}
	return topic, nil
}

// Supervisors is the resolver for the supervisors field.
func (r *studentTopicCouncilResolver) Supervisors(ctx context.Context, obj *model.StudentTopicCouncil) ([]*model.StudentTopicSupervisor, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.SupervisorByTopicCouncilId != nil {
		supervisors, err := loaders.SupervisorByTopicCouncilId.Load(ctx, obj.ID)
		if err != nil {
			return nil, err
		}
		return supervisors, nil
	}
	supervisor, err := r.Ctrl.GetSupervisorByTopicId(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return supervisor, nil
}

// Council is the resolver for the council field.
func (r *studentTopicCouncilResolver) Council(ctx context.Context, obj *model.StudentTopicCouncil) (*model.StudentCouncil, error) {
	if obj.CouncilCode == nil {
		return nil, nil
	}
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.CouncilByIdForStudent != nil {
		council, err := loaders.CouncilByIdForStudent.Load(ctx, *obj.CouncilCode)
		if err != nil {
			return nil, err
		}
		return council, nil
	}
	council, err := r.Ctrl.GetCouncilByIdForStudent(ctx, *obj.CouncilCode)
	if err != nil {
		return nil, err
	}
	return council, nil
}

// Teacher is the resolver for the teacher field.
func (r *studentTopicSupervisorResolver) Teacher(ctx context.Context, obj *model.StudentTopicSupervisor) (*model.StudentTeacherInfo, error) {
	loaders := dataloader.GetLoaders(ctx)
	if loaders != nil && loaders.TeacherInfoById != nil {
		teachers, err := loaders.TeacherInfoById.Load(ctx, obj.TeacherSupervisorCode)
		if err != nil {
			return nil, err
		}
		return teachers, nil
	}
	teacher, err := r.Ctrl.GetTeacherInfoById(ctx, obj.TeacherSupervisorCode)
	if err != nil {
		return nil, err
	}
	return teacher, nil
}

// StudentCouncil returns generated.StudentCouncilResolver implementation.
func (r *Resolver) StudentCouncil() generated.StudentCouncilResolver {
	return &studentCouncilResolver{r}
}

// StudentDefenceInfo returns generated.StudentDefenceInfoResolver implementation.
func (r *Resolver) StudentDefenceInfo() generated.StudentDefenceInfoResolver {
	return &studentDefenceInfoResolver{r}
}

// StudentEnrollment returns generated.StudentEnrollmentResolver implementation.
func (r *Resolver) StudentEnrollment() generated.StudentEnrollmentResolver {
	return &studentEnrollmentResolver{r}
}

// StudentGradeDefence returns generated.StudentGradeDefenceResolver implementation.
func (r *Resolver) StudentGradeDefence() generated.StudentGradeDefenceResolver {
	return &studentGradeDefenceResolver{r}
}

// StudentTopic returns generated.StudentTopicResolver implementation.
func (r *Resolver) StudentTopic() generated.StudentTopicResolver { return &studentTopicResolver{r} }

// StudentTopicCouncil returns generated.StudentTopicCouncilResolver implementation.
func (r *Resolver) StudentTopicCouncil() generated.StudentTopicCouncilResolver {
	return &studentTopicCouncilResolver{r}
}

// StudentTopicSupervisor returns generated.StudentTopicSupervisorResolver implementation.
func (r *Resolver) StudentTopicSupervisor() generated.StudentTopicSupervisorResolver {
	return &studentTopicSupervisorResolver{r}
}

type studentCouncilResolver struct{ *Resolver }
type studentDefenceInfoResolver struct{ *Resolver }
type studentEnrollmentResolver struct{ *Resolver }
type studentGradeDefenceResolver struct{ *Resolver }
type studentTopicResolver struct{ *Resolver }
type studentTopicCouncilResolver struct{ *Resolver }
type studentTopicSupervisorResolver struct{ *Resolver }
