// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// ReviewerMutation - Mutations cho giao vien phan bien
// Entry point: mutation { teacher { reviewer { ... } } }
type AffairMutation struct {
	// Tao moi giao vien
	CreateTeacher *Teacher `json:"createTeacher"`
	// Cap nhat thong tin giao vien
	UpdateTeacher *Teacher `json:"updateTeacher"`
	// Xoa giao vien
	DeleteTeacher bool `json:"deleteTeacher"`
	// Tao moi sinh vien
	CreateStudent *Student `json:"createStudent"`
	// Cap nhat thong tin sinh vien
	UpdateStudent *Student `json:"updateStudent"`
	// Xoa sinh vien
	DeleteStudent bool `json:"deleteStudent"`
	// Tao semester moi
	CreateSemester *Semester `json:"createSemester"`
	// Cap nhat semester
	UpdateSemester *Semester `json:"updateSemester"`
	// Xoa semester
	DeleteSemester bool `json:"deleteSemester"`
	// Tao major moi
	CreateMajor *Major `json:"createMajor"`
	// Cap nhat major
	UpdateMajor *Major `json:"updateMajor"`
	// Xoa major
	DeleteMajor bool `json:"deleteMajor"`
	// Tao faculty moi
	CreateFaculty *Faculty `json:"createFaculty"`
	// Cap nhat faculty
	UpdateFaculty *Faculty `json:"updateFaculty"`
	// Xoa faculty
	DeleteFaculty bool `json:"deleteFaculty"`
	// Phe duyet council (cho phep set thoi gian)
	ApproveCouncil *Council `json:"approveCouncil"`
	// Cap nhat council
	UpdateCouncil *Council `json:"updateCouncil"`
	// Xoa council
	DeleteCouncil bool `json:"deleteCouncil"`
	// Phe duyet topic lan 2 (approved_2)
	ApproveTopic *Topic `json:"approveTopic"`
	// Tu choi topic
	RejectTopic *Topic `json:"rejectTopic"`
	// Cap nhat topic
	UpdateTopic *Topic `json:"updateTopic"`
	// Xoa topic
	DeleteTopic bool `json:"deleteTopic"`
}

// ReviewerQuery - Queries cho giao vien phan bien
// Entry point: teacher { reviewer { ... } }
type AffairQuery struct {
	// Lay danh sach giao vien
	Teachers *TeacherListResponse `json:"teachers"`
	// Lay chi tiet giao vien
	TeacherDetail *Teacher `json:"teacherDetail,omitempty"`
	// Lay danh sach sinh vien
	Students *StudentListResponse `json:"students"`
	// Lay chi tiet sinh vien
	StudentDetail *Student `json:"studentDetail,omitempty"`
	// Lay danh sach semester
	Semesters *SemesterListResponse `json:"semesters"`
	// Lay chi tiet semester
	SemesterDetail *Semester `json:"semesterDetail,omitempty"`
	// Lay danh sach major
	Majors *MajorListResponse `json:"majors"`
	// Lay chi tiet major
	MajorDetail *Major `json:"majorDetail,omitempty"`
	// Lay danh sach faculty
	Faculties *FacultyListResponse `json:"faculties"`
	// Lay chi tiet faculty
	FacultyDetail *Faculty `json:"facultyDetail,omitempty"`
	// Lay danh sach topic voi day du thong tin
	Topics *TopicListResponse `json:"topics"`
	// Lay chi tiet topic
	TopicDetail *Topic `json:"topicDetail,omitempty"`
	// Lay danh sach enrollment
	Enrollments *EnrollmentListResponse `json:"enrollments"`
	// Lay chi tiet enrollment voi day du thong tin
	EnrollmentDetail *Enrollment `json:"enrollmentDetail,omitempty"`
	// Lay danh sach council
	Councils *CouncilListResponse `json:"councils"`
	// Lay chi tiet council
	CouncilDetail *Council `json:"councilDetail,omitempty"`
	// Lay danh sach defence cua mot council
	DefencesByCouncil *DefenceListResponse `json:"defencesByCouncil"`
	// Lay danh sach grade defence
	GradeDefences *GradeDefenceListResponse `json:"gradeDefences"`
}

// Council - Unified type
// RBAC check o field resolver:
// - topicCouncils: null neu la student
type Council struct {
	ID            string          `json:"id"`
	Title         string          `json:"title"`
	MajorCode     string          `json:"majorCode"`
	SemesterCode  string          `json:"semesterCode"`
	TimeStart     *time.Time      `json:"timeStart,omitempty"`
	CreatedAt     *time.Time      `json:"createdAt,omitempty"`
	UpdatedAt     *time.Time      `json:"updatedAt,omitempty"`
	CreatedBy     *string         `json:"createdBy,omitempty"`
	UpdatedBy     *string         `json:"updatedBy,omitempty"`
	Major         *MajorInfo      `json:"major,omitempty"`
	Semester      *SemesterInfo   `json:"semester,omitempty"`
	Defences      []*Defence      `json:"defences,omitempty"`
	TopicCouncils []*TopicCouncil `json:"topicCouncils,omitempty"`
}

type CouncilListResponse struct {
	Total int32      `json:"total"`
	Data  []*Council `json:"data"`
}

// CouncilMemberMutation - Mutations cho thanh vien hoi dong
// Entry point: mutation { teacher { council { ... } } }
type CouncilMemberMutation struct {
	// Tao grade defence
	CreateGradeDefence *GradeDefence `json:"createGradeDefence"`
	// Cap nhat grade defence
	UpdateGradeDefence *GradeDefence `json:"updateGradeDefence"`
	// Them criterion vao grade defence
	AddCriterion *GradeDefenceCriterion `json:"addCriterion"`
	// Cap nhat criterion
	UpdateCriterion *GradeDefenceCriterion `json:"updateCriterion"`
	// Xoa criterion
	DeleteCriterion bool `json:"deleteCriterion"`
}

// CouncilMemberQuery - Queries cho thanh vien hoi dong
// Entry point: teacher { council { ... } }
type CouncilMemberQuery struct {
	// Lay danh sach defence assignments cua giao vien
	Defences *DefenceListResponse `json:"defences"`
}

type CreateCouncilInput struct {
	Title     string `json:"title"`
	MajorCode string `json:"majorCode"`
}

type CreateDefenceInput struct {
	Title       string          `json:"title"`
	CouncilCode string          `json:"councilCode"`
	TeacherCode string          `json:"teacherCode"`
	Position    DefencePosition `json:"position"`
}

type CreateFacultyInput struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Ms    string `json:"ms"`
}

type CreateGradeDefenceCriterionInput struct {
	GradeDefenceCode string `json:"gradeDefenceCode"`
	Name             string `json:"name"`
	Score            string `json:"score"`
	MaxScore         string `json:"maxScore"`
}

type CreateGradeDefenceInput struct {
	DefenceCode    string  `json:"defenceCode"`
	EnrollmentCode string  `json:"enrollmentCode"`
	Note           *string `json:"note,omitempty"`
	TotalScore     *int32  `json:"totalScore,omitempty"`
}

type CreateMajorInput struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	FacultyCode string `json:"facultyCode"`
	Ms          string `json:"ms"`
}

type CreateSemesterInput struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

type CreateStudentInput struct {
	ID           string  `json:"id"`
	Email        string  `json:"email"`
	Phone        string  `json:"phone"`
	Username     string  `json:"username"`
	Gender       Gender  `json:"gender"`
	MajorCode    string  `json:"majorCode"`
	ClassCode    *string `json:"classCode,omitempty"`
	SemesterCode string  `json:"semesterCode"`
	Mssv         string  `json:"mssv"`
}

type CreateTeacherInput struct {
	ID           string            `json:"id"`
	Email        string            `json:"email"`
	Username     string            `json:"username"`
	Gender       Gender            `json:"gender"`
	MajorCode    string            `json:"majorCode"`
	SemesterCode string            `json:"semesterCode"`
	Msgv         string            `json:"msgv"`
	Roles        []*RoleSystemRole `json:"roles"`
}

type CreateTopicCouncilInput struct {
	TopicCode string    `json:"topicCode"`
	TimeStart time.Time `json:"timeStart"`
	TimeEnd   time.Time `json:"timeEnd"`
	Students  []string  `json:"students"`
}

type CreateTopicInput struct {
	Title       string     `json:"title"`
	TitleEn     string     `json:"titleEn"`
	Description string     `json:"description"`
	Students    []string   `json:"students"`
	Stage       TopicStage `json:"stage"`
	Curriculum  *string    `json:"curriculum,omitempty"`
	TimeStart   time.Time  `json:"timeStart"`
	TimeEnd     time.Time  `json:"timeEnd"`
}

// Defence - Unified type (thay the CouncilDefence)
type Defence struct {
	ID            string          `json:"id"`
	Title         string          `json:"title"`
	CouncilCode   string          `json:"councilCode"`
	TeacherCode   string          `json:"teacherCode"`
	Position      DefencePosition `json:"position"`
	CreatedAt     *time.Time      `json:"createdAt,omitempty"`
	UpdatedAt     *time.Time      `json:"updatedAt,omitempty"`
	CreatedBy     *string         `json:"createdBy,omitempty"`
	UpdatedBy     *string         `json:"updatedBy,omitempty"`
	Council       *Council        `json:"council,omitempty"`
	Teacher       *Teacher        `json:"teacher,omitempty"`
	GradeDefences []*GradeDefence `json:"gradeDefences,omitempty"`
}

type DefenceListResponse struct {
	Total int32      `json:"total"`
	Data  []*Defence `json:"data"`
}

type DepartmentMutation struct {
	// Tao council moi
	CreateCouncil *Council `json:"createCouncil"`
	// Cap nhat council
	UpdateCouncil *Council `json:"updateCouncil"`
	// Them thanh vien vao council
	AddDefence *Defence `json:"addDefence"`
	// Xoa thanh vien khoi council
	RemoveDefence bool `json:"removeDefence"`
	// Phe duyet topic lan 1 (approved_1)
	ApproveTopicStage1 *Topic `json:"approveTopicStage1"`
	// Tu choi topic
	RejectTopicStage1 *Topic `json:"rejectTopicStage1"`
	// Gan topic vao council
	AssignTopicToCouncil *TopicCouncil `json:"assignTopicToCouncil"`
	// Xoa topic khoi council
	RemoveTopicFromCouncil bool `json:"removeTopicFromCouncil"`
}

type DepartmentQuery struct {
	// Lay danh sach giao vien trong bo mon
	Teachers *TeacherListResponse `json:"teachers"`
	// Lay danh sach sinh vien trong bo mon
	Students *StudentListResponse `json:"students"`
	// Lay danh sach semester
	Semesters *SemesterListResponse `json:"semesters"`
	// Lay danh sach major trong bo mon
	Majors *MajorListResponse `json:"majors"`
	// Lay danh sach faculty
	Faculties *FacultyListResponse `json:"faculties"`
	// Lay danh sach tat ca topic trong bo mon
	Topics *TopicListResponse `json:"topics"`
	// Lay danh sach enrollment trong bo mon
	Enrollments *EnrollmentListResponse `json:"enrollments"`
	// Lay danh sach council trong bo mon
	Councils *CouncilListResponse `json:"councils"`
	// Lay danh sach grade defence
	GradeDefences *GradeDefenceListResponse `json:"gradeDefences"`
}

// Enrollment - Unified type (thay the StudentEnrollment, SupervisorEnrollment, etc.)
// RBAC check o field resolver:
// - student: null neu la student role (student khong xem info student khac)
// - gradeDefences: check role
type Enrollment struct {
	ID               string          `json:"id"`
	Title            string          `json:"title"`
	StudentCode      string          `json:"studentCode"`
	TopicCouncilCode string          `json:"topicCouncilCode"`
	FinalCode        *string         `json:"finalCode,omitempty"`
	GradeReviewCode  *string         `json:"gradeReviewCode,omitempty"`
	MidtermCode      *string         `json:"midtermCode,omitempty"`
	CreatedAt        *time.Time      `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time      `json:"updatedAt,omitempty"`
	CreatedBy        *string         `json:"createdBy,omitempty"`
	UpdatedBy        *string         `json:"updatedBy,omitempty"`
	Student          *Student        `json:"student,omitempty"`
	TopicCouncil     *TopicCouncil   `json:"topicCouncil,omitempty"`
	Midterm          *Midterm        `json:"midterm,omitempty"`
	Final            *Final          `json:"final,omitempty"`
	GradeDefences    []*GradeDefence `json:"gradeDefences,omitempty"`
}

type EnrollmentListResponse struct {
	Total int32         `json:"total"`
	Data  []*Enrollment `json:"data"`
}

type Faculty struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Ms        string     `json:"ms"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	CreatedBy *string    `json:"createdBy,omitempty"`
	UpdatedBy *string    `json:"updatedBy,omitempty"`
	Majors    []*Major   `json:"majors"`
}

type FacultyListResponse struct {
	Total int32      `json:"total"`
	Data  []*Faculty `json:"data"`
}

type File struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	File      *string    `json:"file,omitempty"`
	Status    FileStatus `json:"status"`
	Table     FileTable  `json:"table"`
	Option    *string    `json:"option,omitempty"`
	TableID   string     `json:"tableId"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	CreatedBy *string    `json:"createdBy,omitempty"`
	UpdatedBy *string    `json:"updatedBy,omitempty"`
}

type FileListResponse struct {
	Total int32   `json:"total"`
	Data  []*File `json:"data"`
}

type FilterConditionInput struct {
	Field    string         `json:"field"`
	Operator FilterOperator `json:"operator"`
	Values   []string       `json:"values,omitempty"`
}

type FilterCriteriaInput struct {
	Condition *FilterConditionInput `json:"condition,omitempty"`
	Group     *FilterGroupInput     `json:"group,omitempty"`
}

type FilterGroupInput struct {
	Logic   *LogicalCondition      `json:"logic,omitempty"`
	Filters []*FilterCriteriaInput `json:"filters"`
}

type Final struct {
	ID              string      `json:"id"`
	Title           string      `json:"title"`
	SupervisorGrade *int32      `json:"supervisorGrade,omitempty"`
	DepartmentGrade *int32      `json:"departmentGrade,omitempty"`
	FinalGrade      *int32      `json:"finalGrade,omitempty"`
	Status          FinalStatus `json:"status"`
	Notes           *string     `json:"notes,omitempty"`
	CompletionDate  *time.Time  `json:"completionDate,omitempty"`
	CreatedAt       *time.Time  `json:"createdAt,omitempty"`
	UpdatedAt       *time.Time  `json:"updatedAt,omitempty"`
	CreatedBy       *string     `json:"createdBy,omitempty"`
	UpdatedBy       *string     `json:"updatedBy,omitempty"`
	Files           []*File     `json:"files,omitempty"`
}

type FinalListResponse struct {
	Total int32    `json:"total"`
	Data  []*Final `json:"data"`
}

type GradeDefence struct {
	ID             string                   `json:"id"`
	DefenceCode    string                   `json:"defenceCode"`
	EnrollmentCode string                   `json:"enrollmentCode"`
	Note           *string                  `json:"note,omitempty"`
	TotalScore     *int32                   `json:"totalScore,omitempty"`
	CreatedAt      *time.Time               `json:"createdAt,omitempty"`
	UpdatedAt      *time.Time               `json:"updatedAt,omitempty"`
	CreatedBy      *string                  `json:"createdBy,omitempty"`
	UpdatedBy      *string                  `json:"updatedBy,omitempty"`
	Defence        *Defence                 `json:"defence,omitempty"`
	Enrollment     *Enrollment              `json:"enrollment,omitempty"`
	Criteria       []*GradeDefenceCriterion `json:"criteria,omitempty"`
}

type GradeDefenceCriterion struct {
	ID               string     `json:"id"`
	GradeDefenceCode string     `json:"gradeDefenceCode"`
	Name             *string    `json:"name,omitempty"`
	Score            *string    `json:"score,omitempty"`
	MaxScore         *string    `json:"maxScore,omitempty"`
	CreatedAt        *time.Time `json:"createdAt,omitempty"`
	UpdatedAt        *time.Time `json:"updatedAt,omitempty"`
	CreatedBy        *string    `json:"createdBy,omitempty"`
	UpdatedBy        *string    `json:"updatedBy,omitempty"`
}

type GradeDefenceCriterionListResponse struct {
	Total int32                    `json:"total"`
	Data  []*GradeDefenceCriterion `json:"data"`
}

type GradeDefenceListResponse struct {
	Total int32           `json:"total"`
	Data  []*GradeDefence `json:"data"`
}

type GradeFinalInput struct {
	SupervisorGrade int32       `json:"supervisorGrade"`
	Status          FinalStatus `json:"status"`
	Notes           *string     `json:"notes,omitempty"`
}

type GradeMidtermInput struct {
	Grade    int32         `json:"grade"`
	Status   MidtermStatus `json:"status"`
	Feedback *string       `json:"feedback,omitempty"`
}

type Major struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	FacultyCode string     `json:"facultyCode"`
	Ms          string     `json:"ms"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	CreatedBy   *string    `json:"createdBy,omitempty"`
	UpdatedBy   *string    `json:"updatedBy,omitempty"`
}

// Major info - Restricted type de tranh circular query
// Khong co relationships (topics, faculty) de tranh vong lap
type MajorInfo struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	FacultyCode string `json:"facultyCode"`
}

type MajorListResponse struct {
	Total int32    `json:"total"`
	Data  []*Major `json:"data"`
}

type Midterm struct {
	ID        string        `json:"id"`
	Title     string        `json:"title"`
	Grade     *int32        `json:"grade,omitempty"`
	Status    MidtermStatus `json:"status"`
	Feedback  *string       `json:"feedback,omitempty"`
	CreatedAt *time.Time    `json:"createdAt,omitempty"`
	UpdatedAt *time.Time    `json:"updatedAt,omitempty"`
	CreatedBy *string       `json:"createdBy,omitempty"`
	UpdatedBy *string       `json:"updatedBy,omitempty"`
	Files     []*File       `json:"files,omitempty"`
}

type MidtermListResponse struct {
	Total int32      `json:"total"`
	Data  []*Midterm `json:"data"`
}

type Mutation struct {
}

type PaginationInput struct {
	Page       *int32  `json:"page,omitempty"`
	PageSize   *int32  `json:"pageSize,omitempty"`
	SortBy     *string `json:"sortBy,omitempty"`
	Descending *bool   `json:"descending,omitempty"`
}

type Query struct {
}

type RoleSystem struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	TeacherCode  *string        `json:"teacherCode,omitempty"`
	Role         RoleSystemRole `json:"role"`
	SemesterCode string         `json:"semesterCode"`
	Activate     bool           `json:"activate"`
	CreatedAt    *time.Time     `json:"createdAt,omitempty"`
	UpdatedAt    *time.Time     `json:"updatedAt,omitempty"`
	CreatedBy    *string        `json:"createdBy,omitempty"`
	UpdatedBy    *string        `json:"updatedBy,omitempty"`
}

type RoleSystemListResponse struct {
	Total int32         `json:"total"`
	Data  []*RoleSystem `json:"data"`
}

type SearchRequestInput struct {
	Pagination *PaginationInput       `json:"pagination,omitempty"`
	Filters    []*FilterCriteriaInput `json:"filters,omitempty"`
}

type Semester struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	CreatedBy *string    `json:"createdBy,omitempty"`
	UpdatedBy *string    `json:"updatedBy,omitempty"`
}

// Semester info - Restricted type de tranh circular query
// Khong co relationships (students, teachers, topics) de tranh vong lap
type SemesterInfo struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

type SemesterListResponse struct {
	Total int32       `json:"total"`
	Data  []*Semester `json:"data"`
}

type Student struct {
	ID           string     `json:"id"`
	Email        string     `json:"email"`
	Phone        string     `json:"phone"`
	Username     string     `json:"username"`
	Gender       *Gender    `json:"gender,omitempty"`
	MajorCode    string     `json:"majorCode"`
	ClassCode    *string    `json:"classCode,omitempty"`
	SemesterCode string     `json:"semesterCode"`
	Mssv         string     `json:"mssv"`
	CreatedAt    *time.Time `json:"createdAt,omitempty"`
	UpdatedAt    *time.Time `json:"updatedAt,omitempty"`
	CreatedBy    *string    `json:"createdBy,omitempty"`
	UpdatedBy    *string    `json:"updatedBy,omitempty"`
}

type StudentListResponse struct {
	Total int32      `json:"total"`
	Data  []*Student `json:"data"`
}

type StudentMutation struct {
	// Upload file midterm (chi sinh vien moi upload duoc)
	UploadMidtermFile *File `json:"uploadMidtermFile"`
	// Upload file final (chi sinh vien moi upload duoc)
	UploadFinalFile *File `json:"uploadFinalFile"`
}

type StudentQuery struct {
	// Lay thong tin ca nhan cua sinh vien dang dang nhap
	Me *Student `json:"me"`
	// Lay danh sach enrollment cua sinh vien (chi cua minh)
	Enrollments *EnrollmentListResponse `json:"enrollments"`
	// Lay danh sach hoc ky cua sinh vien
	Semesters *SemesterListResponse `json:"semesters"`
}

type Subscription struct {
}

// SupervisorMutation - Mutations cho giao vien huong dan
// Entry point: mutation { teacher { supervisor { ... } } }
type SupervisorMutation struct {
	// Tao topic moi
	CreateTopic *Topic `json:"createTopic"`
	// Tao topic council moi
	CreateTopicCouncil *TopicCouncil `json:"createTopicCouncil"`
	// Cap nhat diem midterm cho sinh vien
	GradeMidterm *Midterm `json:"gradeMidterm"`
	// Phan hoi midterm cho sinh vien
	FeedbackMidterm *Midterm `json:"feedbackMidterm"`
	// Cap nhat diem final cho sinh vien
	GradeFinal *Final `json:"gradeFinal"`
	// Phan hoi final cho sinh vien
	FeedbackFinal *Final `json:"feedbackFinal"`
	// Phe duyet file midterm cua sinh vien
	ApproveMidtermFile *File `json:"approveMidtermFile"`
	// Tu choi file midterm cua sinh vien
	RejectMidtermFile *File `json:"rejectMidtermFile"`
	// Phe duyet file final cua sinh vien
	ApproveFinalFile *File `json:"approveFinalFile"`
	// Tu choi file final cua sinh vien
	RejectFinalFile *File `json:"rejectFinalFile"`
}

// SupervisorQuery - Queries cho giao vien huong dan
// Entry point: teacher { supervisor { ... } }
// Role duoc set khi vao namespace nay
type SupervisorQuery struct {
	// Lay danh sach topic council ma giao vien huong dan
	TopicCouncils *TopicCouncilListResponse `json:"topicCouncils"`
}

type Teacher struct {
	ID           string        `json:"id"`
	Email        string        `json:"email"`
	Username     string        `json:"username"`
	Gender       *Gender       `json:"gender,omitempty"`
	MajorCode    string        `json:"majorCode"`
	SemesterCode string        `json:"semesterCode"`
	Msgv         string        `json:"msgv"`
	CreatedAt    *time.Time    `json:"createdAt,omitempty"`
	UpdatedAt    *time.Time    `json:"updatedAt,omitempty"`
	CreatedBy    *string       `json:"createdBy,omitempty"`
	UpdatedBy    *string       `json:"updatedBy,omitempty"`
	Roles        []*RoleSystem `json:"roles,omitempty"`
}

// Teacher info - Restricted type cho student view
// Khong co field 'roles' vi sensitive
type TeacherInfo struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	Gender    *Gender `json:"gender,omitempty"`
	MajorCode string  `json:"majorCode"`
}

type TeacherListResponse struct {
	Total int32      `json:"total"`
	Data  []*Teacher `json:"data"`
}

type TeacherMutation struct {
	// Cap nhat thong tin ca nhan giao vien
	UpdateProfile *Teacher `json:"updateProfile"`
	// Namespace cho SUPERVISOR (giao vien huong dan) - Set role = 'supervisor'
	Supervisor *SupervisorMutation `json:"supervisor"`
	// Namespace cho COUNCIL MEMBER (thanh vien hoi dong) - Set role = 'council'
	Council *CouncilMemberMutation `json:"council"`
}

type TeacherQuery struct {
	// Lay thong tin ca nhan giao vien
	Me *Teacher `json:"me"`
	// Namespace cho SUPERVISOR (giao vien huong dan) - Set role = 'supervisor'
	Supervisor *SupervisorQuery `json:"supervisor"`
	// Namespace cho COUNCIL MEMBER (thanh vien hoi dong) - Set role = 'council'
	Council *CouncilMemberQuery `json:"council"`
}

// Topic - Unified type
// RBAC check o field resolver:
// - topicCouncils: null neu la student (student chi xem duoc cua minh qua enrollment)
type Topic struct {
	ID            string          `json:"id"`
	Title         string          `json:"title"`
	MajorCode     string          `json:"majorCode"`
	SemesterCode  string          `json:"semesterCode"`
	Status        TopicStatus     `json:"status"`
	PercentStage1 *int32          `json:"percentStage1,omitempty"`
	PercentStage2 *int32          `json:"percentStage2,omitempty"`
	CreatedAt     *time.Time      `json:"createdAt,omitempty"`
	UpdatedAt     *time.Time      `json:"updatedAt,omitempty"`
	CreatedBy     *string         `json:"createdBy,omitempty"`
	UpdatedBy     *string         `json:"updatedBy,omitempty"`
	Major         *MajorInfo      `json:"major,omitempty"`
	Semester      *SemesterInfo   `json:"semester,omitempty"`
	Files         []*File         `json:"files,omitempty"`
	TopicCouncils []*TopicCouncil `json:"topicCouncils,omitempty"`
}

// TopicCouncil - Unified type
// RBAC check o field resolver:
// - enrollments: null neu la student (student khong xem duoc enrollment nguoi khac)
type TopicCouncil struct {
	ID          string                    `json:"id"`
	Title       string                    `json:"title"`
	Stage       TopicStage                `json:"stage"`
	TopicCode   string                    `json:"topicCode"`
	CouncilCode *string                   `json:"councilCode,omitempty"`
	TimeStart   time.Time                 `json:"timeStart"`
	TimeEnd     time.Time                 `json:"timeEnd"`
	CreatedAt   *time.Time                `json:"createdAt,omitempty"`
	UpdatedAt   *time.Time                `json:"updatedAt,omitempty"`
	CreatedBy   *string                   `json:"createdBy,omitempty"`
	UpdatedBy   *string                   `json:"updatedBy,omitempty"`
	Topic       *Topic                    `json:"topic,omitempty"`
	Council     *Council                  `json:"council,omitempty"`
	Supervisors []*TopicCouncilSupervisor `json:"supervisors,omitempty"`
	Enrollments []*Enrollment             `json:"enrollments,omitempty"`
}

type TopicCouncilListResponse struct {
	Total int32           `json:"total"`
	Data  []*TopicCouncil `json:"data"`
}

type TopicCouncilSupervisor struct {
	ID                    string     `json:"id"`
	TeacherSupervisorCode string     `json:"teacherSupervisorCode"`
	TopicCouncilCode      string     `json:"topicCouncilCode"`
	CreatedAt             *time.Time `json:"createdAt,omitempty"`
	UpdatedAt             *time.Time `json:"updatedAt,omitempty"`
	CreatedBy             *string    `json:"createdBy,omitempty"`
	UpdatedBy             *string    `json:"updatedBy,omitempty"`
	Teacher               *Teacher   `json:"teacher,omitempty"`
}

type TopicListResponse struct {
	Total int32    `json:"total"`
	Data  []*Topic `json:"data"`
}

type UpdateCouncilInput struct {
	Title     *string    `json:"title,omitempty"`
	TimeStart *time.Time `json:"timeStart,omitempty"`
}

type UpdateFacultyInput struct {
	Title *string `json:"title,omitempty"`
	Ms    *string `json:"ms,omitempty"`
}

type UpdateGradeDefenceCriterionInput struct {
	Name     *string `json:"name,omitempty"`
	Score    *string `json:"score,omitempty"`
	MaxScore *string `json:"maxScore,omitempty"`
}

type UpdateGradeDefenceInput struct {
	Note       *string `json:"note,omitempty"`
	TotalScore *int32  `json:"totalScore,omitempty"`
}

type UpdateGradeReviewInput struct {
	ReviewGrade *int32       `json:"reviewGrade,omitempty"`
	Status      *FinalStatus `json:"status,omitempty"`
	Notes       *string      `json:"notes,omitempty"`
}

type UpdateMajorInput struct {
	Title       *string `json:"title,omitempty"`
	FacultyCode *string `json:"facultyCode,omitempty"`
	Ms          *string `json:"ms,omitempty"`
}

type UpdateSemesterInput struct {
	Title *string `json:"title,omitempty"`
}

type UpdateStudentInput struct {
	Email        *string `json:"email,omitempty"`
	Phone        *string `json:"phone,omitempty"`
	Username     *string `json:"username,omitempty"`
	Gender       *Gender `json:"gender,omitempty"`
	MajorCode    *string `json:"majorCode,omitempty"`
	ClassCode    *string `json:"classCode,omitempty"`
	SemesterCode *string `json:"semesterCode,omitempty"`
	Mssv         *string `json:"mssv,omitempty"`
}

type UpdateTeacherInput struct {
	Email        *string           `json:"email,omitempty"`
	Username     *string           `json:"username,omitempty"`
	Gender       *Gender           `json:"gender,omitempty"`
	MajorCode    *string           `json:"majorCode,omitempty"`
	SemesterCode *string           `json:"semesterCode,omitempty"`
	Msgv         *string           `json:"msgv,omitempty"`
	Roles        []*RoleSystemRole `json:"roles,omitempty"`
}

type UpdateTeacherProfileInput struct {
	Email    *string `json:"email,omitempty"`
	Username *string `json:"username,omitempty"`
}

type UpdateTopicInput struct {
	Title         *string      `json:"title,omitempty"`
	Status        *TopicStatus `json:"status,omitempty"`
	PercentStage1 *int32       `json:"percentStage1,omitempty"`
	PercentStage2 *int32       `json:"percentStage2,omitempty"`
}

type UploadFileInput struct {
	Title   string  `json:"title"`
	File    string  `json:"file"`
	TableID string  `json:"tableId"`
	Option  *string `json:"option,omitempty"`
}

// Vai tro trong hoi dong bao ve
type DefencePosition string

const (
	DefencePositionPresident DefencePosition = "PRESIDENT"
	DefencePositionSecretary DefencePosition = "SECRETARY"
	DefencePositionReviewer  DefencePosition = "REVIEWER"
	DefencePositionMember    DefencePosition = "MEMBER"
)

var AllDefencePosition = []DefencePosition{
	DefencePositionPresident,
	DefencePositionSecretary,
	DefencePositionReviewer,
	DefencePositionMember,
}

func (e DefencePosition) IsValid() bool {
	switch e {
	case DefencePositionPresident, DefencePositionSecretary, DefencePositionReviewer, DefencePositionMember:
		return true
	}
	return false
}

func (e DefencePosition) String() string {
	return string(e)
}

func (e *DefencePosition) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DefencePosition(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DefencePosition", str)
	}
	return nil
}

func (e DefencePosition) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DefencePosition) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DefencePosition) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Trang thai file
type FileStatus string

const (
	FileStatusFilePending FileStatus = "FILE_PENDING"
	FileStatusApproved    FileStatus = "APPROVED"
	FileStatusRejected    FileStatus = "REJECTED"
)

var AllFileStatus = []FileStatus{
	FileStatusFilePending,
	FileStatusApproved,
	FileStatusRejected,
}

func (e FileStatus) IsValid() bool {
	switch e {
	case FileStatusFilePending, FileStatusApproved, FileStatusRejected:
		return true
	}
	return false
}

func (e FileStatus) String() string {
	return string(e)
}

func (e *FileStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FileStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FileStatus", str)
	}
	return nil
}

func (e FileStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FileStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FileStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Bang dinh kem file
type FileTable string

const (
	FileTableTopic   FileTable = "TOPIC"
	FileTableMidterm FileTable = "MIDTERM"
	FileTableFinal   FileTable = "FINAL"
	FileTableOrder   FileTable = "ORDER"
)

var AllFileTable = []FileTable{
	FileTableTopic,
	FileTableMidterm,
	FileTableFinal,
	FileTableOrder,
}

func (e FileTable) IsValid() bool {
	switch e {
	case FileTableTopic, FileTableMidterm, FileTableFinal, FileTableOrder:
		return true
	}
	return false
}

func (e FileTable) String() string {
	return string(e)
}

func (e *FileTable) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FileTable(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FileTable", str)
	}
	return nil
}

func (e FileTable) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FileTable) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FileTable) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FilterOperator string

const (
	FilterOperatorEqual            FilterOperator = "EQUAL"
	FilterOperatorNotEqual         FilterOperator = "NOT_EQUAL"
	FilterOperatorGreaterThan      FilterOperator = "GREATER_THAN"
	FilterOperatorGreaterThanEqual FilterOperator = "GREATER_THAN_EQUAL"
	FilterOperatorLessThan         FilterOperator = "LESS_THAN"
	FilterOperatorLessThanEqual    FilterOperator = "LESS_THAN_EQUAL"
	FilterOperatorLike             FilterOperator = "LIKE"
	FilterOperatorIn               FilterOperator = "IN"
	FilterOperatorNotIn            FilterOperator = "NOT_IN"
	FilterOperatorIsNull           FilterOperator = "IS_NULL"
	FilterOperatorIsNotNull        FilterOperator = "IS_NOT_NULL"
	FilterOperatorBetween          FilterOperator = "BETWEEN"
)

var AllFilterOperator = []FilterOperator{
	FilterOperatorEqual,
	FilterOperatorNotEqual,
	FilterOperatorGreaterThan,
	FilterOperatorGreaterThanEqual,
	FilterOperatorLessThan,
	FilterOperatorLessThanEqual,
	FilterOperatorLike,
	FilterOperatorIn,
	FilterOperatorNotIn,
	FilterOperatorIsNull,
	FilterOperatorIsNotNull,
	FilterOperatorBetween,
}

func (e FilterOperator) IsValid() bool {
	switch e {
	case FilterOperatorEqual, FilterOperatorNotEqual, FilterOperatorGreaterThan, FilterOperatorGreaterThanEqual, FilterOperatorLessThan, FilterOperatorLessThanEqual, FilterOperatorLike, FilterOperatorIn, FilterOperatorNotIn, FilterOperatorIsNull, FilterOperatorIsNotNull, FilterOperatorBetween:
		return true
	}
	return false
}

func (e FilterOperator) String() string {
	return string(e)
}

func (e *FilterOperator) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FilterOperator(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FilterOperator", str)
	}
	return nil
}

func (e FilterOperator) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FilterOperator) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FilterOperator) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Trang thai do an cuoi cung
type FinalStatus string

const (
	FinalStatusPending   FinalStatus = "PENDING"
	FinalStatusPassed    FinalStatus = "PASSED"
	FinalStatusFailed    FinalStatus = "FAILED"
	FinalStatusCompleted FinalStatus = "COMPLETED"
)

var AllFinalStatus = []FinalStatus{
	FinalStatusPending,
	FinalStatusPassed,
	FinalStatusFailed,
	FinalStatusCompleted,
}

func (e FinalStatus) IsValid() bool {
	switch e {
	case FinalStatusPending, FinalStatusPassed, FinalStatusFailed, FinalStatusCompleted:
		return true
	}
	return false
}

func (e FinalStatus) String() string {
	return string(e)
}

func (e *FinalStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FinalStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FinalStatus", str)
	}
	return nil
}

func (e FinalStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FinalStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FinalStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Gioi tinh
type Gender string

const (
	GenderMale   Gender = "MALE"
	GenderFemale Gender = "FEMALE"
	GenderOther  Gender = "OTHER"
)

var AllGender = []Gender{
	GenderMale,
	GenderFemale,
	GenderOther,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderMale, GenderFemale, GenderOther:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Gender) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Gender) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LogicalCondition string

const (
	LogicalConditionAnd LogicalCondition = "AND"
	LogicalConditionOr  LogicalCondition = "OR"
)

var AllLogicalCondition = []LogicalCondition{
	LogicalConditionAnd,
	LogicalConditionOr,
}

func (e LogicalCondition) IsValid() bool {
	switch e {
	case LogicalConditionAnd, LogicalConditionOr:
		return true
	}
	return false
}

func (e LogicalCondition) String() string {
	return string(e)
}

func (e *LogicalCondition) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LogicalCondition(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LogicalCondition", str)
	}
	return nil
}

func (e LogicalCondition) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LogicalCondition) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LogicalCondition) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Trang thai giua ky
type MidtermStatus string

const (
	MidtermStatusNotSubmitted MidtermStatus = "NOT_SUBMITTED"
	MidtermStatusSubmitted    MidtermStatus = "SUBMITTED"
	MidtermStatusPass         MidtermStatus = "PASS"
	MidtermStatusFail         MidtermStatus = "FAIL"
)

var AllMidtermStatus = []MidtermStatus{
	MidtermStatusNotSubmitted,
	MidtermStatusSubmitted,
	MidtermStatusPass,
	MidtermStatusFail,
}

func (e MidtermStatus) IsValid() bool {
	switch e {
	case MidtermStatusNotSubmitted, MidtermStatusSubmitted, MidtermStatusPass, MidtermStatusFail:
		return true
	}
	return false
}

func (e MidtermStatus) String() string {
	return string(e)
}

func (e *MidtermStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MidtermStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MidtermStatus", str)
	}
	return nil
}

func (e MidtermStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MidtermStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MidtermStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleTeacher Role = "TEACHER"
	RoleStudent Role = "STUDENT"
)

var AllRole = []Role{
	RoleTeacher,
	RoleStudent,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleTeacher, RoleStudent:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Vai tro STATIC trong he thong
// Role dong (Supervisor, Reviewer, Council Member) duoc xac dinh qua:
// - Supervisor: bang Topic_council_supervisor
// - Reviewer: bang Grade_review
// - Council Member: bang Defence
type RoleSystemRole string

const (
	RoleSystemRoleAcademicAffairsStaff RoleSystemRole = "ACADEMIC_AFFAIRS_STAFF"
	RoleSystemRoleDepartmentLecturer   RoleSystemRole = "DEPARTMENT_LECTURER"
	RoleSystemRoleTeacher              RoleSystemRole = "TEACHER"
)

var AllRoleSystemRole = []RoleSystemRole{
	RoleSystemRoleAcademicAffairsStaff,
	RoleSystemRoleDepartmentLecturer,
	RoleSystemRoleTeacher,
}

func (e RoleSystemRole) IsValid() bool {
	switch e {
	case RoleSystemRoleAcademicAffairsStaff, RoleSystemRoleDepartmentLecturer, RoleSystemRoleTeacher:
		return true
	}
	return false
}

func (e RoleSystemRole) String() string {
	return string(e)
}

func (e *RoleSystemRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoleSystemRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoleSystemRole", str)
	}
	return nil
}

func (e RoleSystemRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RoleSystemRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RoleSystemRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Giai doan de tai
type TopicStage string

const (
	TopicStageStageDacn TopicStage = "STAGE_DACN"
	TopicStageStageLvtn TopicStage = "STAGE_LVTN"
)

var AllTopicStage = []TopicStage{
	TopicStageStageDacn,
	TopicStageStageLvtn,
}

func (e TopicStage) IsValid() bool {
	switch e {
	case TopicStageStageDacn, TopicStageStageLvtn:
		return true
	}
	return false
}

func (e TopicStage) String() string {
	return string(e)
}

func (e *TopicStage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TopicStage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TopicStage", str)
	}
	return nil
}

func (e TopicStage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TopicStage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TopicStage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Trang thai de tai
type TopicStatus string

const (
	TopicStatusSubmit         TopicStatus = "SUBMIT"
	TopicStatusTopicPending   TopicStatus = "TOPIC_PENDING"
	TopicStatusApproved1      TopicStatus = "APPROVED_1"
	TopicStatusApproved2      TopicStatus = "APPROVED_2"
	TopicStatusInProgress     TopicStatus = "IN_PROGRESS"
	TopicStatusTopicCompleted TopicStatus = "TOPIC_COMPLETED"
	TopicStatusRejected       TopicStatus = "REJECTED"
)

var AllTopicStatus = []TopicStatus{
	TopicStatusSubmit,
	TopicStatusTopicPending,
	TopicStatusApproved1,
	TopicStatusApproved2,
	TopicStatusInProgress,
	TopicStatusTopicCompleted,
	TopicStatusRejected,
}

func (e TopicStatus) IsValid() bool {
	switch e {
	case TopicStatusSubmit, TopicStatusTopicPending, TopicStatusApproved1, TopicStatusApproved2, TopicStatusInProgress, TopicStatusTopicCompleted, TopicStatusRejected:
		return true
	}
	return false
}

func (e TopicStatus) String() string {
	return string(e)
}

func (e *TopicStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TopicStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TopicStatus", str)
	}
	return nil
}

func (e TopicStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TopicStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TopicStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
