version: '3.8'

services:
  academic:
    build:
      context: ../../..
      dockerfile: src/service/academic/Dockerfile
    image: thaily/lvtn-academic:latest
    container_name: academic_service
    env_file:
      - academic.env
    ports:
      - "50051:50051"
    volumes:
      - .:/app/service:ro
      - ../../../logs:/app/logs
    networks:
      - academic_network
    restart: unless-stopped

networks:
  academic_network:
    driver: bridge
