syntax = "proto3";

package academic;

option go_package = "./academic";

import "google/protobuf/timestamp.proto";
import "proto/common/common.proto";

// ============= Semester =============
message Semester {
  string id = 1;
  string title = 2;
  google.protobuf.Timestamp created_at = 3;
  google.protobuf.Timestamp updated_at = 4;
  string created_by = 5;
  string updated_by = 6;
}

message SemesterAction {
  string title = 1;
  string created_by = 2;
  string updated_by = 3;
}

message GetSemesterRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message CreateSemesterRequest {
  SemesterAction semester = 1;
}

message UpdateSemesterRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
  SemesterAction semester = 3;
}

message DeleteSemesterRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message SemesterResponse {
  Semester semester = 1;
}

message DeleteSemesterResponse {
  bool success = 1;
}

message ListSemestersRequest {
  common.SearchRequest search = 1;
}

message ListSemestersResponse {
  repeated Semester semesters = 1;
  int32 total = 2;
  int32 page = 3;
  int32 page_size = 4;
}

// ============= Faculty =============
message Faculty {
  string id = 1;
  string title = 2;
  google.protobuf.Timestamp created_at = 3;
  google.protobuf.Timestamp updated_at = 4;
  string created_by = 5;
  string updated_by = 6;
  string ms = 7;
}

message FacultyAction {
  string id = 1;
  string title = 2;
  string created_by = 3;
  string updated_by = 4;
  string ms = 5;
}

message GetFacultyRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message CreateFacultyRequest {
  FacultyAction faculty = 1;
}

message UpdateFacultyRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
  FacultyAction faculty = 3;
}

message DeleteFacultyRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message FacultyResponse {
  Faculty faculty = 1;
}

message DeleteFacultyResponse {
  bool success = 1;
}

message ListFacultiesRequest {
  common.SearchRequest search = 1;
}

message ListFacultiesResponse {
  repeated Faculty faculties = 1;
  int32 total = 2;
  int32 page = 3;
  int32 page_size = 4;
}


// ============= Major =============
message Major {
  string id = 1;
  string title = 2;
  string faculty_code = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  string created_by = 6;
  string updated_by = 7;
  string ms = 8;
}

message MajorAction {
  string id = 1;
  string title = 2;
  string faculty_code = 3;
  string created_by = 4;
  string updated_by = 5;
  string ms = 6;
}

message GetMajorRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message CreateMajorRequest {
  MajorAction major = 1;
}

message UpdateMajorRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
  MajorAction major = 3;
}

message DeleteMajorRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message MajorResponse {
  Major major = 1;
}

message DeleteMajorResponse {
  bool success = 1;
}

message ListMajorsRequest {
  common.SearchRequest search = 1;
}

message ListMajorsResponse {
  repeated Major majors = 1;
  int32 total = 2;
  int32 page = 3;
  int32 page_size = 4;
}


// ============= Service =============
service AcademicService {
  // Semester
  rpc CreateSemester(CreateSemesterRequest) returns (SemesterResponse);
  rpc GetSemester(GetSemesterRequest) returns (SemesterResponse);
  rpc UpdateSemester(UpdateSemesterRequest) returns (SemesterResponse);
  rpc DeleteSemester(DeleteSemesterRequest) returns (DeleteSemesterResponse);
  rpc ListSemesters(ListSemestersRequest) returns (ListSemestersResponse);

  // Faculty
  rpc CreateFaculty(CreateFacultyRequest) returns (FacultyResponse);
  rpc GetFaculty(GetFacultyRequest) returns (FacultyResponse);
  rpc UpdateFaculty(UpdateFacultyRequest) returns (FacultyResponse);
  rpc DeleteFaculty(DeleteFacultyRequest) returns (DeleteFacultyResponse);
  rpc ListFaculties(ListFacultiesRequest) returns (ListFacultiesResponse);

  // Major
  rpc CreateMajor(CreateMajorRequest) returns (MajorResponse);
  rpc GetMajor(GetMajorRequest) returns (MajorResponse);
  rpc UpdateMajor(UpdateMajorRequest) returns (MajorResponse);
  rpc DeleteMajor(DeleteMajorRequest) returns (DeleteMajorResponse);
  rpc ListMajors(ListMajorsRequest) returns (ListMajorsResponse);
}
