version: '3.8'

services:
  user:
    build:
      context: ../../..
      dockerfile: src/service/user/Dockerfile
    image: thaily/lvtn-user:latest
    container_name: user_service
    env_file:
      - user.env
    ports:
      - "50056:50056"
    volumes:
      - .:/app/service:ro
      - ../../../logs:/app/logs
    networks:
      - user_network
    restart: unless-stopped

networks:
  user_network:
    driver: bridge
