// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/thesis/thesis.proto

package thesis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThesisService_CreateMidterm_FullMethodName    = "/thesis.ThesisService/CreateMidterm"
	ThesisService_GetMidterm_FullMethodName       = "/thesis.ThesisService/GetMidterm"
	ThesisService_UpdateMidterm_FullMethodName    = "/thesis.ThesisService/UpdateMidterm"
	ThesisService_DeleteMidterm_FullMethodName    = "/thesis.ThesisService/DeleteMidterm"
	ThesisService_ListMidterms_FullMethodName     = "/thesis.ThesisService/ListMidterms"
	ThesisService_CreateFinal_FullMethodName      = "/thesis.ThesisService/CreateFinal"
	ThesisService_GetFinal_FullMethodName         = "/thesis.ThesisService/GetFinal"
	ThesisService_UpdateFinal_FullMethodName      = "/thesis.ThesisService/UpdateFinal"
	ThesisService_DeleteFinal_FullMethodName      = "/thesis.ThesisService/DeleteFinal"
	ThesisService_ListFinals_FullMethodName       = "/thesis.ThesisService/ListFinals"
	ThesisService_CreateEnrollment_FullMethodName = "/thesis.ThesisService/CreateEnrollment"
	ThesisService_GetEnrollment_FullMethodName    = "/thesis.ThesisService/GetEnrollment"
	ThesisService_UpdateEnrollment_FullMethodName = "/thesis.ThesisService/UpdateEnrollment"
	ThesisService_DeleteEnrollment_FullMethodName = "/thesis.ThesisService/DeleteEnrollment"
	ThesisService_ListEnrollments_FullMethodName  = "/thesis.ThesisService/ListEnrollments"
	ThesisService_CreateTopic_FullMethodName      = "/thesis.ThesisService/CreateTopic"
	ThesisService_GetTopic_FullMethodName         = "/thesis.ThesisService/GetTopic"
	ThesisService_UpdateTopic_FullMethodName      = "/thesis.ThesisService/UpdateTopic"
	ThesisService_DeleteTopic_FullMethodName      = "/thesis.ThesisService/DeleteTopic"
	ThesisService_ListTopics_FullMethodName       = "/thesis.ThesisService/ListTopics"
)

// ThesisServiceClient is the client API for ThesisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============= Service =============
type ThesisServiceClient interface {
	// Midterm
	CreateMidterm(ctx context.Context, in *CreateMidtermRequest, opts ...grpc.CallOption) (*CreateMidtermResponse, error)
	GetMidterm(ctx context.Context, in *GetMidtermRequest, opts ...grpc.CallOption) (*GetMidtermResponse, error)
	UpdateMidterm(ctx context.Context, in *UpdateMidtermRequest, opts ...grpc.CallOption) (*UpdateMidtermResponse, error)
	DeleteMidterm(ctx context.Context, in *DeleteMidtermRequest, opts ...grpc.CallOption) (*DeleteMidtermResponse, error)
	ListMidterms(ctx context.Context, in *ListMidtermsRequest, opts ...grpc.CallOption) (*ListMidtermsResponse, error)
	// Final
	CreateFinal(ctx context.Context, in *CreateFinalRequest, opts ...grpc.CallOption) (*CreateFinalResponse, error)
	GetFinal(ctx context.Context, in *GetFinalRequest, opts ...grpc.CallOption) (*GetFinalResponse, error)
	UpdateFinal(ctx context.Context, in *UpdateFinalRequest, opts ...grpc.CallOption) (*UpdateFinalResponse, error)
	DeleteFinal(ctx context.Context, in *DeleteFinalRequest, opts ...grpc.CallOption) (*DeleteFinalResponse, error)
	ListFinals(ctx context.Context, in *ListFinalsRequest, opts ...grpc.CallOption) (*ListFinalsResponse, error)
	// Enrollment
	CreateEnrollment(ctx context.Context, in *CreateEnrollmentRequest, opts ...grpc.CallOption) (*CreateEnrollmentResponse, error)
	GetEnrollment(ctx context.Context, in *GetEnrollmentRequest, opts ...grpc.CallOption) (*GetEnrollmentResponse, error)
	UpdateEnrollment(ctx context.Context, in *UpdateEnrollmentRequest, opts ...grpc.CallOption) (*UpdateEnrollmentResponse, error)
	DeleteEnrollment(ctx context.Context, in *DeleteEnrollmentRequest, opts ...grpc.CallOption) (*DeleteEnrollmentResponse, error)
	ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error)
	// Topic
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error)
	GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*GetTopicResponse, error)
	UpdateTopic(ctx context.Context, in *UpdateTopicRequest, opts ...grpc.CallOption) (*UpdateTopicResponse, error)
	DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*DeleteTopicResponse, error)
	ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error)
}

type thesisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThesisServiceClient(cc grpc.ClientConnInterface) ThesisServiceClient {
	return &thesisServiceClient{cc}
}

func (c *thesisServiceClient) CreateMidterm(ctx context.Context, in *CreateMidtermRequest, opts ...grpc.CallOption) (*CreateMidtermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMidtermResponse)
	err := c.cc.Invoke(ctx, ThesisService_CreateMidterm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) GetMidterm(ctx context.Context, in *GetMidtermRequest, opts ...grpc.CallOption) (*GetMidtermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMidtermResponse)
	err := c.cc.Invoke(ctx, ThesisService_GetMidterm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) UpdateMidterm(ctx context.Context, in *UpdateMidtermRequest, opts ...grpc.CallOption) (*UpdateMidtermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMidtermResponse)
	err := c.cc.Invoke(ctx, ThesisService_UpdateMidterm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) DeleteMidterm(ctx context.Context, in *DeleteMidtermRequest, opts ...grpc.CallOption) (*DeleteMidtermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMidtermResponse)
	err := c.cc.Invoke(ctx, ThesisService_DeleteMidterm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) ListMidterms(ctx context.Context, in *ListMidtermsRequest, opts ...grpc.CallOption) (*ListMidtermsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMidtermsResponse)
	err := c.cc.Invoke(ctx, ThesisService_ListMidterms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) CreateFinal(ctx context.Context, in *CreateFinalRequest, opts ...grpc.CallOption) (*CreateFinalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFinalResponse)
	err := c.cc.Invoke(ctx, ThesisService_CreateFinal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) GetFinal(ctx context.Context, in *GetFinalRequest, opts ...grpc.CallOption) (*GetFinalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFinalResponse)
	err := c.cc.Invoke(ctx, ThesisService_GetFinal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) UpdateFinal(ctx context.Context, in *UpdateFinalRequest, opts ...grpc.CallOption) (*UpdateFinalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFinalResponse)
	err := c.cc.Invoke(ctx, ThesisService_UpdateFinal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) DeleteFinal(ctx context.Context, in *DeleteFinalRequest, opts ...grpc.CallOption) (*DeleteFinalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFinalResponse)
	err := c.cc.Invoke(ctx, ThesisService_DeleteFinal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) ListFinals(ctx context.Context, in *ListFinalsRequest, opts ...grpc.CallOption) (*ListFinalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFinalsResponse)
	err := c.cc.Invoke(ctx, ThesisService_ListFinals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) CreateEnrollment(ctx context.Context, in *CreateEnrollmentRequest, opts ...grpc.CallOption) (*CreateEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEnrollmentResponse)
	err := c.cc.Invoke(ctx, ThesisService_CreateEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) GetEnrollment(ctx context.Context, in *GetEnrollmentRequest, opts ...grpc.CallOption) (*GetEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnrollmentResponse)
	err := c.cc.Invoke(ctx, ThesisService_GetEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) UpdateEnrollment(ctx context.Context, in *UpdateEnrollmentRequest, opts ...grpc.CallOption) (*UpdateEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEnrollmentResponse)
	err := c.cc.Invoke(ctx, ThesisService_UpdateEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) DeleteEnrollment(ctx context.Context, in *DeleteEnrollmentRequest, opts ...grpc.CallOption) (*DeleteEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEnrollmentResponse)
	err := c.cc.Invoke(ctx, ThesisService_DeleteEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrollmentsResponse)
	err := c.cc.Invoke(ctx, ThesisService_ListEnrollments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, ThesisService_CreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*GetTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopicResponse)
	err := c.cc.Invoke(ctx, ThesisService_GetTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) UpdateTopic(ctx context.Context, in *UpdateTopicRequest, opts ...grpc.CallOption) (*UpdateTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTopicResponse)
	err := c.cc.Invoke(ctx, ThesisService_UpdateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*DeleteTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTopicResponse)
	err := c.cc.Invoke(ctx, ThesisService_DeleteTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thesisServiceClient) ListTopics(ctx context.Context, in *ListTopicsRequest, opts ...grpc.CallOption) (*ListTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopicsResponse)
	err := c.cc.Invoke(ctx, ThesisService_ListTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThesisServiceServer is the server API for ThesisService service.
// All implementations must embed UnimplementedThesisServiceServer
// for forward compatibility.
//
// ============= Service =============
type ThesisServiceServer interface {
	// Midterm
	CreateMidterm(context.Context, *CreateMidtermRequest) (*CreateMidtermResponse, error)
	GetMidterm(context.Context, *GetMidtermRequest) (*GetMidtermResponse, error)
	UpdateMidterm(context.Context, *UpdateMidtermRequest) (*UpdateMidtermResponse, error)
	DeleteMidterm(context.Context, *DeleteMidtermRequest) (*DeleteMidtermResponse, error)
	ListMidterms(context.Context, *ListMidtermsRequest) (*ListMidtermsResponse, error)
	// Final
	CreateFinal(context.Context, *CreateFinalRequest) (*CreateFinalResponse, error)
	GetFinal(context.Context, *GetFinalRequest) (*GetFinalResponse, error)
	UpdateFinal(context.Context, *UpdateFinalRequest) (*UpdateFinalResponse, error)
	DeleteFinal(context.Context, *DeleteFinalRequest) (*DeleteFinalResponse, error)
	ListFinals(context.Context, *ListFinalsRequest) (*ListFinalsResponse, error)
	// Enrollment
	CreateEnrollment(context.Context, *CreateEnrollmentRequest) (*CreateEnrollmentResponse, error)
	GetEnrollment(context.Context, *GetEnrollmentRequest) (*GetEnrollmentResponse, error)
	UpdateEnrollment(context.Context, *UpdateEnrollmentRequest) (*UpdateEnrollmentResponse, error)
	DeleteEnrollment(context.Context, *DeleteEnrollmentRequest) (*DeleteEnrollmentResponse, error)
	ListEnrollments(context.Context, *ListEnrollmentsRequest) (*ListEnrollmentsResponse, error)
	// Topic
	CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error)
	GetTopic(context.Context, *GetTopicRequest) (*GetTopicResponse, error)
	UpdateTopic(context.Context, *UpdateTopicRequest) (*UpdateTopicResponse, error)
	DeleteTopic(context.Context, *DeleteTopicRequest) (*DeleteTopicResponse, error)
	ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error)
	mustEmbedUnimplementedThesisServiceServer()
}

// UnimplementedThesisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThesisServiceServer struct{}

func (UnimplementedThesisServiceServer) CreateMidterm(context.Context, *CreateMidtermRequest) (*CreateMidtermResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMidterm not implemented")
}
func (UnimplementedThesisServiceServer) GetMidterm(context.Context, *GetMidtermRequest) (*GetMidtermResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMidterm not implemented")
}
func (UnimplementedThesisServiceServer) UpdateMidterm(context.Context, *UpdateMidtermRequest) (*UpdateMidtermResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMidterm not implemented")
}
func (UnimplementedThesisServiceServer) DeleteMidterm(context.Context, *DeleteMidtermRequest) (*DeleteMidtermResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMidterm not implemented")
}
func (UnimplementedThesisServiceServer) ListMidterms(context.Context, *ListMidtermsRequest) (*ListMidtermsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMidterms not implemented")
}
func (UnimplementedThesisServiceServer) CreateFinal(context.Context, *CreateFinalRequest) (*CreateFinalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFinal not implemented")
}
func (UnimplementedThesisServiceServer) GetFinal(context.Context, *GetFinalRequest) (*GetFinalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFinal not implemented")
}
func (UnimplementedThesisServiceServer) UpdateFinal(context.Context, *UpdateFinalRequest) (*UpdateFinalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFinal not implemented")
}
func (UnimplementedThesisServiceServer) DeleteFinal(context.Context, *DeleteFinalRequest) (*DeleteFinalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFinal not implemented")
}
func (UnimplementedThesisServiceServer) ListFinals(context.Context, *ListFinalsRequest) (*ListFinalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFinals not implemented")
}
func (UnimplementedThesisServiceServer) CreateEnrollment(context.Context, *CreateEnrollmentRequest) (*CreateEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnrollment not implemented")
}
func (UnimplementedThesisServiceServer) GetEnrollment(context.Context, *GetEnrollmentRequest) (*GetEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnrollment not implemented")
}
func (UnimplementedThesisServiceServer) UpdateEnrollment(context.Context, *UpdateEnrollmentRequest) (*UpdateEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEnrollment not implemented")
}
func (UnimplementedThesisServiceServer) DeleteEnrollment(context.Context, *DeleteEnrollmentRequest) (*DeleteEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEnrollment not implemented")
}
func (UnimplementedThesisServiceServer) ListEnrollments(context.Context, *ListEnrollmentsRequest) (*ListEnrollmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnrollments not implemented")
}
func (UnimplementedThesisServiceServer) CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedThesisServiceServer) GetTopic(context.Context, *GetTopicRequest) (*GetTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopic not implemented")
}
func (UnimplementedThesisServiceServer) UpdateTopic(context.Context, *UpdateTopicRequest) (*UpdateTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTopic not implemented")
}
func (UnimplementedThesisServiceServer) DeleteTopic(context.Context, *DeleteTopicRequest) (*DeleteTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTopic not implemented")
}
func (UnimplementedThesisServiceServer) ListTopics(context.Context, *ListTopicsRequest) (*ListTopicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedThesisServiceServer) mustEmbedUnimplementedThesisServiceServer() {}
func (UnimplementedThesisServiceServer) testEmbeddedByValue()                       {}

// UnsafeThesisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThesisServiceServer will
// result in compilation errors.
type UnsafeThesisServiceServer interface {
	mustEmbedUnimplementedThesisServiceServer()
}

func RegisterThesisServiceServer(s grpc.ServiceRegistrar, srv ThesisServiceServer) {
	// If the following call pancis, it indicates UnimplementedThesisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThesisService_ServiceDesc, srv)
}

func _ThesisService_CreateMidterm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMidtermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).CreateMidterm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_CreateMidterm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).CreateMidterm(ctx, req.(*CreateMidtermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_GetMidterm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMidtermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).GetMidterm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_GetMidterm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).GetMidterm(ctx, req.(*GetMidtermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_UpdateMidterm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMidtermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).UpdateMidterm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_UpdateMidterm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).UpdateMidterm(ctx, req.(*UpdateMidtermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_DeleteMidterm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMidtermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).DeleteMidterm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_DeleteMidterm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).DeleteMidterm(ctx, req.(*DeleteMidtermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_ListMidterms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMidtermsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).ListMidterms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_ListMidterms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).ListMidterms(ctx, req.(*ListMidtermsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_CreateFinal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFinalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).CreateFinal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_CreateFinal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).CreateFinal(ctx, req.(*CreateFinalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_GetFinal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFinalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).GetFinal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_GetFinal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).GetFinal(ctx, req.(*GetFinalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_UpdateFinal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFinalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).UpdateFinal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_UpdateFinal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).UpdateFinal(ctx, req.(*UpdateFinalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_DeleteFinal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFinalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).DeleteFinal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_DeleteFinal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).DeleteFinal(ctx, req.(*DeleteFinalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_ListFinals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFinalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).ListFinals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_ListFinals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).ListFinals(ctx, req.(*ListFinalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_CreateEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).CreateEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_CreateEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).CreateEnrollment(ctx, req.(*CreateEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_GetEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).GetEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_GetEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).GetEnrollment(ctx, req.(*GetEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_UpdateEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).UpdateEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_UpdateEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).UpdateEnrollment(ctx, req.(*UpdateEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_DeleteEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).DeleteEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_DeleteEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).DeleteEnrollment(ctx, req.(*DeleteEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_ListEnrollments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrollmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).ListEnrollments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_ListEnrollments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).ListEnrollments(ctx, req.(*ListEnrollmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_GetTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).GetTopic(ctx, req.(*GetTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_UpdateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).UpdateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_UpdateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).UpdateTopic(ctx, req.(*UpdateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_DeleteTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).DeleteTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_DeleteTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).DeleteTopic(ctx, req.(*DeleteTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThesisService_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThesisServiceServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThesisService_ListTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThesisServiceServer).ListTopics(ctx, req.(*ListTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThesisService_ServiceDesc is the grpc.ServiceDesc for ThesisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThesisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thesis.ThesisService",
	HandlerType: (*ThesisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMidterm",
			Handler:    _ThesisService_CreateMidterm_Handler,
		},
		{
			MethodName: "GetMidterm",
			Handler:    _ThesisService_GetMidterm_Handler,
		},
		{
			MethodName: "UpdateMidterm",
			Handler:    _ThesisService_UpdateMidterm_Handler,
		},
		{
			MethodName: "DeleteMidterm",
			Handler:    _ThesisService_DeleteMidterm_Handler,
		},
		{
			MethodName: "ListMidterms",
			Handler:    _ThesisService_ListMidterms_Handler,
		},
		{
			MethodName: "CreateFinal",
			Handler:    _ThesisService_CreateFinal_Handler,
		},
		{
			MethodName: "GetFinal",
			Handler:    _ThesisService_GetFinal_Handler,
		},
		{
			MethodName: "UpdateFinal",
			Handler:    _ThesisService_UpdateFinal_Handler,
		},
		{
			MethodName: "DeleteFinal",
			Handler:    _ThesisService_DeleteFinal_Handler,
		},
		{
			MethodName: "ListFinals",
			Handler:    _ThesisService_ListFinals_Handler,
		},
		{
			MethodName: "CreateEnrollment",
			Handler:    _ThesisService_CreateEnrollment_Handler,
		},
		{
			MethodName: "GetEnrollment",
			Handler:    _ThesisService_GetEnrollment_Handler,
		},
		{
			MethodName: "UpdateEnrollment",
			Handler:    _ThesisService_UpdateEnrollment_Handler,
		},
		{
			MethodName: "DeleteEnrollment",
			Handler:    _ThesisService_DeleteEnrollment_Handler,
		},
		{
			MethodName: "ListEnrollments",
			Handler:    _ThesisService_ListEnrollments_Handler,
		},
		{
			MethodName: "CreateTopic",
			Handler:    _ThesisService_CreateTopic_Handler,
		},
		{
			MethodName: "GetTopic",
			Handler:    _ThesisService_GetTopic_Handler,
		},
		{
			MethodName: "UpdateTopic",
			Handler:    _ThesisService_UpdateTopic_Handler,
		},
		{
			MethodName: "DeleteTopic",
			Handler:    _ThesisService_DeleteTopic_Handler,
		},
		{
			MethodName: "ListTopics",
			Handler:    _ThesisService_ListTopics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/thesis/thesis.proto",
}
