syntax = "proto3";

package thesis;

option go_package = "./thesis";

import "google/protobuf/timestamp.proto";

import "proto/common/common.proto";

// ============= Enums =============
enum MidtermStatus {
  NOT_SUBMITTED = 0;
  SUBMITTED = 1;
  PASS = 2;
  FAIL = 3;
}

enum FinalStatus {
  PENDING = 0;
  PASSED = 1;
  FAILED = 2;
  COMPLETED = 3;
}

enum TopicStatus {
  SUBMIT = 0;
  TOPIC_PENDING = 1;
  APPROVED_1 = 2;
  APPROVED_2 = 3;
  IN_PROGRESS = 4;
  TOPIC_COMPLETED = 5;
  REJECTED = 6;
}

enum TopicStage {
  STAGE_DACN = 0;
  STAGE_LVTN = 1;
}

// ============= Midterm =============
message Midterm {
  string id = 1;
  string title = 2;
  int32 grade = 3;
  MidtermStatus status = 4;
  string feedback = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
  string created_by = 8;
  string updated_by = 9;
  string enrollment_code = 10;
}

message MidtermAction {
  string title = 1;
  int32 grade = 2;
  MidtermStatus status = 3;
  string feedback = 4;
  string created_by = 5;
  string updated_by = 6;
  string enrollment_code = 7;
}

message MidtermResponse {
  Midterm midterm = 1;
}

message CreateMidtermRequest {
  MidtermAction midterm = 1;
}

message GetMidtermRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message UpdateMidtermRequest {
  string id = 1;
  MidtermAction midterm = 2;
  repeated common.FilterCriteria filter = 3;
}

message DeleteMidtermRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message DeleteMidtermResponse {
  bool success = 1;
}

message ListMidtermsRequest {
  common.SearchRequest search = 1;
}

message ListMidtermsResponse {
  repeated Midterm midterms = 1;
  int32 total = 2;
  int32 page = 3;
  int32 page_size = 4;
}

// ============= Final =============
message Final {
  string id = 1;
  string title = 2;
  int32 supervisor_grade = 3;
  string enrollment_code = 4;
  int32 final_grade = 5;
  FinalStatus status = 6;
  string notes = 7;
  google.protobuf.Timestamp completion_date = 8;
  google.protobuf.Timestamp created_at = 9;
  google.protobuf.Timestamp updated_at = 10;
  string created_by = 11;
  string updated_by = 12;
}

message FinalAction {
  string title = 1;
  int32 supervisor_grade = 2;
  string enrollment_code = 3;
  int32 final_grade = 4;
  FinalStatus status = 5;
  string notes = 6;
  google.protobuf.Timestamp completion_date = 7;
  string created_by = 8;
  string updated_by = 9;
}

message FinalResponse {
  Final final = 1;
}

message CreateFinalRequest {
  FinalAction final = 1;
}

message GetFinalRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message UpdateFinalRequest {
  string id = 1;
  FinalAction final = 2;
  repeated common.FilterCriteria filter = 3;
}

message DeleteFinalRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message DeleteFinalResponse {
  bool success = 1;
}

message ListFinalsRequest {
  common.SearchRequest search = 1;
}

message ListFinalsResponse {
  repeated Final finals = 1;
  int32 total = 2;
  int32 page = 3;
  int32 page_size = 4;
}

// ============= Enrollment =============
message Enrollment {
  string id = 1;
  string title = 2;
  string student_code = 3;
  string topic_council_code = 4;
  string final_code = 5;
  string grade_review_code = 6;
  string midterm_code = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
  string created_by = 10;
  string updated_by = 11;
}

message EnrollmentAction {
  string title = 1;
  string student_code = 2;
  string topic_council_code = 3;
  string final_code = 4;
  string grade_review_code = 5;
  string midterm_code = 6;
  string created_by = 7;
  string updated_by = 8;
}

message EnrollmentResponse {
  Enrollment enrollment = 1;
}

message CreateEnrollmentRequest {
  EnrollmentAction enrollment = 1;
}

message GetEnrollmentRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message UpdateEnrollmentRequest {
  string id = 1;
  EnrollmentAction enrollment = 2;
  repeated common.FilterCriteria filter = 3;
}

message DeleteEnrollmentRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message DeleteEnrollmentResponse {
  bool success = 1;
}

message ListEnrollmentsRequest {
  common.SearchRequest search = 1;
}

message ListEnrollmentsResponse {
  repeated Enrollment enrollments = 1;
  int32 total = 2;
  int32 page = 3;
  int32 page_size = 4;
}

// ============= Topic =============
message Topic {
  string id = 1;
  string title = 2;
  string title_en = 3;
  string description = 4;
  string curriculum = 5;
  string major_code = 6;
  string semester_code = 7;
  TopicStatus status = 8;
  google.protobuf.Timestamp created_at = 9;
  google.protobuf.Timestamp updated_at = 10;
  int32 percent_stage_1 = 11;
  int32 percent_stage_2 = 12;
  string created_by = 13;
  string updated_by = 14;
}

message TopicAction {
  string title = 1;
  string title_en = 2;
  string description = 3;
  string major_code = 4;
  string curriculum = 5;
  string semester_code = 6;
  TopicStatus status = 7;
  int32 percent_stage_1 = 8;
  int32 percent_stage_2 = 9;
  string created_by = 10;
  string updated_by = 11;
}

message TopicResponse {
  Topic topic = 1;
}

message CreateTopicRequest {
  TopicAction topic = 1;
}

message GetTopicRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message UpdateTopicRequest {
  string id = 1;
  TopicAction topic = 2;
  repeated common.FilterCriteria filter = 3;
}

message DeleteTopicRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message DeleteTopicResponse {
  bool success = 1;
}

message ListTopicsRequest {
  common.SearchRequest search = 1;
}

message ListTopicsResponse {
  repeated Topic topics = 1;
  int32 total = 2;
  int32 page = 3;
  int32 page_size = 4;
}

// ============= TopicCouncil =============
message TopicCouncil {
  string id = 1;
  string title = 2;
  TopicStage stage = 3;
  string topic_code = 4;
  string council_code = 5;
  google.protobuf.Timestamp time_start = 6;
  google.protobuf.Timestamp time_end = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
  string created_by = 10;
  string updated_by = 11;
}

message TopicCouncilAction {
  string title = 1;
  TopicStage stage = 2;
  string topic_code = 3;
  optional string council_code = 4;
  google.protobuf.Timestamp time_start = 5;
  google.protobuf.Timestamp time_end = 6;
  string created_by = 7;
  string updated_by = 8;
}

message TopicCouncilResponse {
  TopicCouncil topic_council = 1;
}

message CreateTopicCouncilRequest {
  TopicCouncilAction topic_council = 1;
}

message GetTopicCouncilRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message UpdateTopicCouncilRequest {
  string id = 1;
  TopicCouncilAction topic_council = 2;
  repeated common.FilterCriteria filter = 3;
}

message DeleteTopicCouncilRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message DeleteTopicCouncilResponse {
  bool success = 1;
}

message ListTopicCouncilsRequest {
  common.SearchRequest search = 1;
}

message ListTopicCouncilsResponse {
  repeated TopicCouncil topic_councils = 1;
  int32 total = 2;
  int32 page = 3;
  int32 page_size = 4;
}

// ============= TopicCouncilSupervisor =============
message TopicCouncilSupervisor {
  string id = 1;
  string teacher_supervisor_code = 2;
  string topic_council_code = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  string created_by = 6;
  string updated_by = 7;
}

message TopicCouncilSupervisorAction {
  string teacher_supervisor_code = 1;
  string topic_council_code = 2;
  string created_by = 3;
  string updated_by = 4;
}

message TopicCouncilSupervisorResponse {
  TopicCouncilSupervisor topic_council_supervisor = 1;
}

message CreateTopicCouncilSupervisorRequest {
  TopicCouncilSupervisorAction topic_council_supervisor = 1;
}

message GetTopicCouncilSupervisorRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message UpdateTopicCouncilSupervisorRequest {
  string id = 1;
  TopicCouncilSupervisorAction topic_council_supervisor = 2;
  repeated common.FilterCriteria filter = 3;
}

message DeleteTopicCouncilSupervisorRequest {
  string id = 1;
  repeated common.FilterCriteria filter = 2;
}

message DeleteTopicCouncilSupervisorResponse {
  bool success = 1;
}

message ListTopicCouncilSupervisorsRequest {
  common.SearchRequest search = 1;
}

message ListTopicCouncilSupervisorsResponse {
  repeated TopicCouncilSupervisor topic_council_supervisors = 1;
  int32 total = 2;
  int32 page = 3;
  int32 page_size = 4;
}

// ============= Service =============
service ThesisService {
  // Midterm
  rpc CreateMidterm(CreateMidtermRequest) returns (MidtermResponse);
  rpc GetMidterm(GetMidtermRequest) returns (MidtermResponse);
  rpc UpdateMidterm(UpdateMidtermRequest) returns (MidtermResponse);
  rpc DeleteMidterm(DeleteMidtermRequest) returns (DeleteMidtermResponse);
  rpc ListMidterms(ListMidtermsRequest) returns (ListMidtermsResponse);

  // Final
  rpc CreateFinal(CreateFinalRequest) returns (FinalResponse);
  rpc GetFinal(GetFinalRequest) returns (FinalResponse);
  rpc UpdateFinal(UpdateFinalRequest) returns (FinalResponse);
  rpc DeleteFinal(DeleteFinalRequest) returns (DeleteFinalResponse);
  rpc ListFinals(ListFinalsRequest) returns (ListFinalsResponse);

  // Enrollment
  rpc CreateEnrollment(CreateEnrollmentRequest) returns (EnrollmentResponse);
  rpc GetEnrollment(GetEnrollmentRequest) returns (EnrollmentResponse);
  rpc UpdateEnrollment(UpdateEnrollmentRequest) returns (EnrollmentResponse);
  rpc DeleteEnrollment(DeleteEnrollmentRequest) returns (DeleteEnrollmentResponse);
  rpc ListEnrollments(ListEnrollmentsRequest) returns (ListEnrollmentsResponse);

  // Topic
  rpc CreateTopic(CreateTopicRequest) returns (TopicResponse);
  rpc GetTopic(GetTopicRequest) returns (TopicResponse);
  rpc UpdateTopic(UpdateTopicRequest) returns (TopicResponse);
  rpc DeleteTopic(DeleteTopicRequest) returns (DeleteTopicResponse);
  rpc ListTopics(ListTopicsRequest) returns (ListTopicsResponse);

  // TopicCouncil
  rpc CreateTopicCouncil(CreateTopicCouncilRequest) returns (TopicCouncilResponse);
  rpc GetTopicCouncil(GetTopicCouncilRequest) returns (TopicCouncilResponse);
  rpc UpdateTopicCouncil(UpdateTopicCouncilRequest) returns (TopicCouncilResponse);
  rpc DeleteTopicCouncil(DeleteTopicCouncilRequest) returns (DeleteTopicCouncilResponse);
  rpc ListTopicCouncils(ListTopicCouncilsRequest) returns (ListTopicCouncilsResponse);

  // TopicCouncilSupervisor
  rpc CreateTopicCouncilSupervisor(CreateTopicCouncilSupervisorRequest) returns (TopicCouncilSupervisorResponse);
  rpc GetTopicCouncilSupervisor(GetTopicCouncilSupervisorRequest) returns (TopicCouncilSupervisorResponse);
  rpc UpdateTopicCouncilSupervisor(UpdateTopicCouncilSupervisorRequest) returns (TopicCouncilSupervisorResponse);
  rpc DeleteTopicCouncilSupervisor(DeleteTopicCouncilSupervisorRequest) returns (DeleteTopicCouncilSupervisorResponse);
  rpc ListTopicCouncilSupervisors(ListTopicCouncilSupervisorsRequest) returns (ListTopicCouncilSupervisorsResponse);
}
